"""Verifies descape/scenario_new.py: the byte-splice that generates a blank
N x N .aoe2scenario map from the shipped 120x120 donor, for File > New Map's
size submenu and Custom size... dialog.

The centerpiece is test_generated_matches_real_game_export: a 120->120
self-test is identity by construction (splicing the donor's own size back in
touches nothing), which catches only a length error in the splice, not an
offset error -- the same non-discriminating shape tools/strip_units.py's own
no-op self-test has (see that module's docstring). What actually discriminates
a correct splice from a subtly wrong one is reproducing real game output the
donor never saw: tests/fixtures/real_blank_{240x240,480x480}.aoe2scenario are
real AoE2:DE exports (moved from descape/templates/, see scenario_io.py's
BLANK_TEMPLATE_SIZES comment) that this module's splice reproduces
byte-for-byte modulo exactly one deliberately-inherited field.

These two fixtures are byte oracles, not regenerable assets. Regenerating them
from the donor via this same generator would make the comparison a tautology
and silently stop testing anything -- never do that; re-export from the real
game only.
"""

from __future__ import annotations

import dataclasses
import struct
from pathlib import Path

import pytest

from descape.scenario_io import (
    BLANK_TEMPLATE_PATH,
    TERRAIN_STRUCT_SIZE,
    load_map_and_units,
)
from descape.scenario_new import (
    BLANK_TERRAIN_STRUCT,
    MAX_MAP_TILES,
    MIN_MAP_TILES,
    STANDARD_MAP_SIZES,
    BlankGenerationError,
    MapSizeError,
    blank_body,
    blank_scenario_bytes,
    load_blank_scenario,
    validate_tiles,
)
from descape.scenario_write import _compress_bytes

FIXTURES = Path(__file__).resolve().parent / "fixtures"
REAL_ORACLE_PATHS = {240: FIXTURES / "real_blank_240x240.aoe2scenario", 480: FIXTURES / "real_blank_480x480.aoe2scenario"}

DONOR_FILENAME_FIELD = b"blank120.aoe2scenario"


@pytest.fixture(scope="module")
def donor():
    return load_map_and_units(BLANK_TEMPLATE_PATH)


def test_generate_120_is_byte_identity_with_donor(donor) -> None:
    """Identity by construction -- splicing the donor's own size back in
    changes nothing, so this only proves the splice doesn't corrupt the
    trivial case. See module docstring for why this alone isn't enough."""
    assert blank_body(donor, 120) == donor.decompressed_body


@pytest.mark.parametrize("tiles", sorted(REAL_ORACLE_PATHS))
def test_generated_matches_real_game_export(donor, tiles: int) -> None:
    oracle = load_map_and_units(REAL_ORACLE_PATHS[tiles])
    generated = blank_body(donor, tiles)

    # DataHeader.filename is the one field the splice deliberately never
    # touches (see scenario_new.py's module docstring: it's length-prefixed
    # and terminates DataHeader, so rewriting it would shift every offset
    # after it). Locate it by content rather than a hardcoded offset, so this
    # test stays meaningful if the donor is ever legitimately re-exported.
    i = donor.decompressed_body.index(DONOR_FILENAME_FIELD)
    n = len(DONOR_FILENAME_FIELD)
    oracle_field = oracle.decompressed_body[i : i + n]
    assert oracle_field == f"blank{tiles}.aoe2scenario".encode()

    patched = generated[:i] + oracle_field + generated[i + n :]
    # The load-bearing assertion: our generated bytes, plus the one field we
    # deliberately inherit, are exactly what AoE2:DE itself wrote.
    assert patched == oracle.decompressed_body

    # Bonus assertion only -- real, but fragile in a different way: it also
    # requires header_bytes[12] (timestamp_of_last_save) to line up, and it
    # depends on this machine's zlib producing byte-identical raw-deflate
    # output to the game's own compressor on this input. A future zlib bump
    # could break this line with no code change; it must never be the thing
    # that reads as a splice bug if it fails while the assertion above passes.
    header = donor.header_bytes[:12] + oracle.header_bytes[12:13] + donor.header_bytes[13:]
    assert header + _compress_bytes(patched) == REAL_ORACLE_PATHS[tiles].read_bytes()


@pytest.mark.parametrize("tiles", (120, 137, 168, 240))
def test_generated_sizes_load_blank_and_square(tiles: int) -> None:
    """Full reload through the real loader for a representative sample.
    137 is deliberately odd, not a multiple of 8 (220 in the real corpus
    already proves the game tolerates that shape). 480 is checked structurally
    in test_generated_480_structurally_without_a_full_reload instead of here
    -- a full reload of a 480 body alone takes ~5s, and this parametrization
    should stay cheap. Do not extend this tuple to "complete" it without
    re-checking that cost."""
    scenario = load_blank_scenario(tiles)
    mm = scenario.map_manager
    assert mm.map_width == mm.map_height == tiles
    assert scenario.map_is_square
    assert scenario.terrain_write_supported
    assert scenario.units_write_supported
    assert sum(len(units) for units in scenario.unit_manager.units) == 0
    assert all(t.terrain_id == 0 and t.elevation == 0 and t.layer == -1 for t in mm.terrain)


def test_generated_480_structurally_without_a_full_reload(donor) -> None:
    body = blank_body(donor, 480)
    off = donor.terrain_block_offset
    assert struct.unpack_from("<ii", body, off - 8) == (480, 480)
    terrain = body[off : off + TERRAIN_STRUCT_SIZE * 480 * 480]
    assert len(terrain) == TERRAIN_STRUCT_SIZE * 480 * 480
    assert terrain == BLANK_TERRAIN_STRUCT * (480 * 480)


def test_generated_bytes_survive_a_disk_round_trip(tmp_path) -> None:
    data = blank_scenario_bytes(168)
    out = tmp_path / "new_168.aoe2scenario"
    out.write_bytes(data)

    reloaded = load_map_and_units(out)
    assert reloaded.map_manager.map_width == reloaded.map_manager.map_height == 168
    assert reloaded.terrain_write_supported


def test_everything_outside_map_size_and_terrain_is_carried_verbatim(donor) -> None:
    off = donor.terrain_block_offset
    old_w, old_h = donor.map_manager.map_width, donor.map_manager.map_height
    old_end = off + TERRAIN_STRUCT_SIZE * old_w * old_h

    generated = blank_body(donor, 200)
    new_end = (off - 8) + 8 + TERRAIN_STRUCT_SIZE * 200 * 200

    assert generated[: off - 8] == donor.decompressed_body[: off - 8]
    assert generated[new_end:] == donor.decompressed_body[old_end:]


@pytest.mark.parametrize("tiles", (MAX_MAP_TILES + 1, MIN_MAP_TILES - 1, 0, -1))
def test_rejects_sizes_outside_bounds(donor, tiles: int) -> None:
    with pytest.raises(MapSizeError):
        validate_tiles(tiles)
    with pytest.raises(MapSizeError):
        blank_body(donor, tiles)


def test_rejects_non_int_size(donor) -> None:
    with pytest.raises(MapSizeError):
        validate_tiles(168.0)
    with pytest.raises(MapSizeError):
        validate_tiles(True)


def test_min_map_tiles_loads_blank_and_square(donor) -> None:
    """MIN_MAP_TILES (61) is the structural floor set by the fixed (60, 60)
    editor camera -- see scenario_new.py's own comment on that constant.
    Confirms the splice itself is sound at the boundary; whether the real
    game accepts a scenario this small has not been confirmed in-game
    (tracked in this project's private planning docs, not a public path)."""
    scenario = load_blank_scenario(MIN_MAP_TILES, donor)
    mm = scenario.map_manager
    assert mm.map_width == mm.map_height == MIN_MAP_TILES
    assert scenario.map_is_square
    assert scenario.terrain_write_supported
    assert all(t.terrain_id == 0 and t.elevation == 0 and t.layer == -1 for t in mm.terrain)


def test_refuses_unverified_donor(donor) -> None:
    unsupported = dataclasses.replace(donor, terrain_write_supported=False, terrain_block_offset=-1)
    with pytest.raises(BlankGenerationError):
        blank_body(unsupported, 168)


def test_refuses_donor_whose_size_field_disagrees(donor) -> None:
    off = donor.terrain_block_offset
    corrupted_body = bytearray(donor.decompressed_body)
    struct.pack_into("<i", corrupted_body, off - 8, 121)  # was 120
    corrupted = dataclasses.replace(donor, decompressed_body=bytes(corrupted_body))
    with pytest.raises(BlankGenerationError):
        blank_body(corrupted, 168)


def test_standard_map_sizes_matches_real_corpus() -> None:
    """Pins the empirical size list this whole feature is built on: every
    real campaign scenario in examples/ uses exactly one of these seven
    sizes. If this ever needs to change, it should be a deliberate,
    evidenced edit to STANDARD_MAP_SIZES, not a silent drift."""
    assert STANDARD_MAP_SIZES == (120, 144, 168, 200, 220, 240, 480)


@pytest.mark.corpus
def test_map_size_precedes_terrain_block_in_every_corpus_file(scenario_path) -> None:
    """The generic form of the splice's core structural assumption: that the
    raw (map_width, map_height) s32 pair sits at terrain_block_offset - 8 in
    every real file, not just the three templates this module was designed
    against. Confirmed passing on the full examples/ corpus (scenario
    versions 1.37-1.58) -- this is what would catch a future DE scenario
    version reordering Map's tail fields."""
    scenario = load_map_and_units(scenario_path)
    if not scenario.terrain_write_supported:
        pytest.skip(f"{scenario_path.name}: terrain block failed load-time verification")
    off = scenario.terrain_block_offset
    w, h = scenario.map_manager.map_width, scenario.map_manager.map_height
    assert struct.unpack_from("<ii", scenario.decompressed_body, off - 8) == (w, h)
