#!/usr/bin/env python3
"""Regenerates config.example.yaml from descape/settings.py,
descape/asset_source.py and descape/content_roots.py, so the example file can't silently drift out of
sync with the real config schema the way it had (missing dark_mode/
window_size, missing 16 of 22 keybind entries, one dead tool_pencil key
left over from before the tools list was restructured -- none of that
caught until someone happened to compare them by hand).

    python3 tools/gen_config_example.py          # write config.example.yaml
    python3 tools/gen_config_example.py --check  # exit 1 if it's stale

tests/test_config_example.py runs the --check equivalent as part of the
default pytest tier, so a settings.py change that isn't matched here fails
the normal test run, not just a hand pass.
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from descape import (
    asset_source,
    content_roots,
    edge_ticks,
    grid_overlay,
    iso_geometry,
    settings,
    terrain_style,
    themes,
    unit_pick,
    view_layers,
)

OUT_PATH = ROOT / "config.example.yaml"

_QUALITY_LABELS = ", ".join(f"{n}={label}" for n, label in sorted(settings.GRAPHICS_QUALITY_LABELS.items()))
_AUTOSAVE_INTERVALS = ", ".join(str(n) for n in settings.AUTOSAVE_INTERVAL_CHOICES)
_AUTOSAVE_RETENTIONS = ", ".join(str(n) for n in settings.AUTOSAVE_RETENTION_CHOICES)

_ELEV_STEP_STOP_COUNT = len(settings.ELEV_STEP_PCT_STOPS)

_TICK_INTERVALS = " or ".join(str(n) for n in edge_ticks.TICK_INTERVALS)
_FOOTPRINT_SCOPES = " or ".join(unit_pick.FOOTPRINT_SCOPES)
_STACK_BADGE_POSITIONS = ", ".join(pid for pid, _label in settings.STACK_BADGE_POSITIONS)
_TRIGGER_STATUS_MARKERS = ", ".join(mid for mid, _label in settings.TRIGGER_STATUS_MARKERS)
_TERRAIN_STYLES = ", ".join(terrain_style.TERRAIN_STYLES)
_VIEW_LAYER_LABELS = textwrap.fill(
    ", ".join(f"{spec.layer_id} ({spec.label.replace('&', '')})" for spec in view_layers.LAYERS),
    width=76,
    subsequent_indent="# ",
)
_THEME_PRESETS = textwrap.fill(", ".join(themes.PRESETS), width=76, subsequent_indent="# ")
_THEME_ROLES = textwrap.fill(", ".join(themes.ROLE_IDS), width=76, subsequent_indent="# ")


def render() -> str:
    keybinds_yaml = yaml.safe_dump(
        {action_id: default for action_id, _label, default in settings.REBINDABLE_ACTIONS},
        default_flow_style=False,
        sort_keys=False,
    )
    keybinds_block = "\n".join(f"  {line}" for line in keybinds_yaml.splitlines())

    overlay_colors_yaml = yaml.safe_dump(
        {color_id: default for color_id, _label, default in settings.OVERLAY_COLORS},
        default_flow_style=False,
        sort_keys=False,
    )
    overlay_colors_block = "\n".join(f"  {line}" for line in overlay_colors_yaml.splitlines())

    overlay_opacity_yaml = yaml.safe_dump(
        {group_id: default for group_id, _label, default in settings.OVERLAY_OPACITIES},
        default_flow_style=False,
        sort_keys=False,
    )
    overlay_opacity_block = "\n".join(f"  {line}" for line in overlay_opacity_yaml.splitlines())

    trigger_status_colors_yaml = yaml.safe_dump(
        {status_id: default for status_id, _label, default in settings.TRIGGER_STATUS_COLORS},
        default_flow_style=False,
        sort_keys=False,
    )
    trigger_status_colors_block = "\n".join(f"  {line}" for line in trigger_status_colors_yaml.splitlines())

    view_layers_yaml = yaml.safe_dump(
        {spec.layer_id: spec.default for spec in view_layers.LAYERS},
        default_flow_style=False,
        sort_keys=False,
    )
    view_layers_block = "\n".join(f"  {line}" for line in view_layers_yaml.splitlines())

    return f"""\
# Example config.yaml -- copy this file to config.yaml in your OS's
# DEscape config directory and edit (Linux: $XDG_CONFIG_HOME/DEscape/ or
# ~/.config/DEscape/; macOS: ~/Library/Application Support/DEscape/;
# Windows: %APPDATA%\\DEscape\\). Every key below is optional; an omitted
# key falls back to the default noted in its comment. Generated by
# tools/gen_config_example.py
# from descape/settings.py and descape/asset_source.py -- run that script
# after changing either, rather than hand-editing this file (also gated by
# tests/test_config_example.py, so a mismatch fails the default test tier).

# Path to your AoE2:DE install (steamapps/common/AoE2DE or similar).
# Enables real per-tile terrain textures instead of averaged flat colors.
# Also settable via the AOE2DE_INSTALL_PATH env var or the viewer's own
# Load button -- see asset_source.py's module docstring for priority order.
# No default: falls back to flat colors if unset everywhere.
aoe2de_install: /path/to/steamapps/common/AoE2DE

# Path to your AoE2:DE profile folder, the one holding numeric per-account
# folders with resources/ and mods/ inside. Only read, never written, and
# optional: without it only the install's own content is offered. Also
# settable via the AOE2DE_PROFILE_PATH env var (checked first). Default:
# detected, as %USERPROFILE%\\Games\\Age of Empires 2 DE on Windows, or on
# Linux as the Proton prefix beside aoe2de_install's Steam library
# (steamapps/compatdata/{content_roots.AOE2DE_STEAM_APP_ID}/pfx/drive_c/users/steamuser/Games/...).
# See content_roots.py's module docstring.
# aoe2de_profile: /path/to/Games/Age of Empires 2 DE

# Language folder under the install's resources/ (e.g. de, fr, es) that
# trigger reference pickers resolve real object/tech display names from --
# see object_catalog.py's resolve_name(). Only takes effect with
# aoe2de_install also set; falls back to the ALL-CAPS library name otherwise.
# Default: "{asset_source.DEFAULT_LANGUAGE}".
language: {asset_source.DEFAULT_LANGUAGE}

# 1-4 ({_QUALITY_LABELS}), see settings.GRAPHICS_QUALITY_LABELS.
# Default: {settings.GRAPHICS_QUALITY_DEFAULT}.
graphics_quality: {settings.GRAPHICS_QUALITY_DEFAULT}

# Stepped elevation height, percent of half_h. Only the {_ELEV_STEP_STOP_COUNT} stops
# {settings.ELEV_STEP_PCT_MIN}-{settings.ELEV_STEP_PCT_MAX} in steps of {settings.ELEV_STEP_PCT_STEP} are legal; anything else snaps to the
# nearest one on read, see settings.ELEV_STEP_PCT_STOPS.
# Default: {iso_geometry.ELEV_STEP_DEFAULT_PCT}.
elev_step_pct: {iso_geometry.ELEV_STEP_DEFAULT_PCT}

# Held-key pan speed for the Pan Up/Down/Left/Right keybinds, in viewport
# pixels per second, Settings > Appearance. Measured in screen pixels like
# the middle-drag pan, so a fixed speed covers fewer tiles the further you
# zoom in. Clamped to {settings.PAN_SPEED_MIN}-{settings.PAN_SPEED_MAX} on read.
# Default: {settings.PAN_SPEED_DEFAULT}.
pan_speed: {settings.PAN_SPEED_DEFAULT}

# Anchor mouse-wheel zoom under the cursor (true) or the view center
# (false). Default: true.
zoom_centered_on_cursor: true

# App-chrome theme preset, Settings > Appearance. One of:
# {_THEME_PRESETS}.
# An unknown id falls back to the default. A config with no `theme` but the
# retired `dark_mode: true` reads as dark. Default: {themes.THEME_DEFAULT}.
theme: {themes.THEME_DEFAULT}

# Per-role chrome colour overrides on top of the preset, "#rrggbb", Settings >
# Appearance > Chrome colours. Roles:
# {_THEME_ROLES}.
# An unknown role or malformed value is ignored. Switching preset clears them.
theme_colors: {{}}

# After a file opens, warm the neighbouring zoom levels' unit sprites in
# idle time so the first zoom doesn't stutter, Settings > Appearance.
# Costs a few seconds of background work per open and some memory; never
# blocks the window. Default: true.
preload_zoom_levels: true

# The toolbar's Elevation View, remembered between launches. One of
# {_TERRAIN_STYLES}. Anything else falls back to the default on read, see
# terrain_style.TERRAIN_STYLES. Default: {settings.TERRAIN_STYLE_DEFAULT}.
terrain_style: {settings.TERRAIN_STYLE_DEFAULT}

# View > Layers, each row on (true) or off (false), remembered between
# launches. Rows:
# {_VIEW_LAYER_LABELS}.
# An unknown row or a non-true/false value keeps that row's default, shown here.
view_layers:
{view_layers_block}

# Ruler-style distance ticks in the void just outside the map border,
# View > Distance Ticks. Default: false.
distance_ticks: false

# Tiles between adjacent minor ticks. Only {_TICK_INTERVALS} are legal; anything
# else falls back to the default on read, see edge_ticks.TICK_INTERVALS.
# Every {edge_ticks.MAJORS_PER_MINOR}th minor is a major and carries a tile number.
# Default: {edge_ticks.TICK_INTERVAL_DEFAULT}.
distance_tick_interval: {edge_ticks.TICK_INTERVAL_DEFAULT}

# In Units mode, a count badge over every spot where a unit is hidden under
# another, View > Show Stacked-Unit Badges. Default: true.
stack_badges: true

# Where each stacked-unit badge sits on its tile, Settings > Appearance.
# One of {_STACK_BADGE_POSITIONS}.
# Anything else falls back to the default on read. The four corners tuck the
# badge inside the tile; above is the original look.
# Default: {settings.STACK_BADGE_POSITION_DEFAULT}.
stack_badge_position: {settings.STACK_BADGE_POSITION_DEFAULT}

# In Units mode, outline each selected unit in its owner's player colour (GAIA
# keeps unit_select), View > Colour Selection by Owner. Default: true.
selection_by_owner: true

# A line on every tile boundary, View > Grid. Default: false.
grid_overlay: false

# Whether the grid drapes over the terrain rather than lying on the flat
# elevation-0 ground plane, View > Grid > Follow Terrain Elevation. No effect
# in Flat. Default: true.
grid_follow_elevation: true

# A circle around each selected building showing its attack range, View >
# Range Rings. Buildings only, and only ones with a range. Default: false.
range_rings: false

# A camera glyph on each player's stored starting view tile, View > Player
# Cameras. Default: false.
camera_markers: false

# The selected trigger's areas, locations and patrol runs drawn on the map,
# View > Trigger Overlay. Draws nothing until a trigger is selected in the
# Triggers panel. Default: true.
trigger_overlay: true

# An outline around every unit footprint in scope, View > Footprint Outlines.
# Default: false.
footprint_outlines: false

# Which units carry one: {_FOOTPRINT_SCOPES}. Anything else falls back to the
# default on read. Default: {unit_pick.FOOTPRINT_SCOPE_DEFAULT}.
footprint_scope: {unit_pick.FOOTPRINT_SCOPE_DEFAULT}

# One outline around each multi-tile footprint instead of one per tile,
# View > Footprint Outlines > Merge tiles. A diagonal gate, and a draped
# Sloped farm over multi-level steps, keep one per tile. Default: false.
footprint_merged: false

# Each outline in its owner's player colour, View > Footprint Outlines >
# Colour by Owner. GAIA keeps the overlay_colors footprint_outline colour.
# Default: false.
footprint_by_owner: false

# How strongly the grid lines blend into the terrain, Settings > Appearance:
# {grid_overlay.BLEND_MIN} is solid black lines, 0 is invisible, {grid_overlay.BLEND_MAX} is solid white ones.
# Out-of-range values clamp. Default: {grid_overlay.BLEND_DEFAULT}.
grid_blend: {grid_overlay.BLEND_DEFAULT}

# Grid line width, Settings > Appearance: map pixels at the current zoom
# level's detail, so roughly half to all of that on screen (screen pixels
# with Follow Terrain Elevation off in Stepped or Sloped). Snaps to the
# nearest of {list(grid_overlay.THICKNESS_STOPS)}. Default: {grid_overlay.THICKNESS_DEFAULT}.
grid_thickness: {grid_overlay.THICKNESS_DEFAULT}

# Main window size in pixels, [width, height]. Persisted automatically on
# resize -- not something you normally set by hand.
# Default: [{settings.DEFAULT_WINDOW_WIDTH}, {settings.DEFAULT_WINDOW_HEIGHT}].
window_size: [{settings.DEFAULT_WINDOW_WIDTH}, {settings.DEFAULT_WINDOW_HEIGHT}]

# Width in pixels of the left info/trigger panel and the map view,
# [left, right]. Persisted automatically when you drag the split -- not
# something you normally set by hand. Omitted entirely until first saved.
# split_sizes: [340, 900]

# Height in pixels of the system log, below the map view. Persisted
# automatically when you drag the split -- not something you normally set by
# hand. Omitted entirely until first saved; until then the log is four text
# lines tall, so unlike split_sizes above there is no fixed default to quote
# here -- it depends on your font. The value below is only an example.
# log_height: 120

# Height in text lines of each multi-line text box you have dragged taller or
# shorter by its bottom edge (trigger form and Messages mode), keyed
# "trigger.<field>" or "messages.<field>". Persisted automatically when you
# release the drag; a double-click on the edge resets the box and removes its
# key. Clamped to {settings.TEXT_BOX_LINES_MIN}-{settings.TEXT_BOX_LINES_MAX}. Omitted entirely until first saved; until then
# every box is six lines tall. The value below is only an example.
# text_box_lines:
#   trigger.description: 12
#   messages.hints: 10

# File > Open Recent, most-recently-opened first. Persisted automatically
# on every open -- not something you normally set by hand. Capped at
# {settings.MAX_RECENT_FILES} entries; omitted entirely until first saved. The value below is
# only an example.
# recent_files:
#   - /path/to/recent_scenario.aoe2scenario

# Every rebindable action (Settings > Keybinds), shown here at its default
# -- see settings.REBINDABLE_ACTIONS for the full id/label/default list.
# Omit an entry to leave that action at its default; "" means unbound.
keybinds:
{keybinds_block}

# Pixel size of the Ruler's on-map measurement label, Settings > Appearance.
# Only {settings.RULER_LABEL_FONT_PX_MIN}-{settings.RULER_LABEL_FONT_PX_MAX} are legal; anything else falls back to the default.
# Default: {settings.RULER_LABEL_FONT_PX_DEFAULT}.
ruler_label_font_px: {settings.RULER_LABEL_FONT_PX_DEFAULT}

# Pixel size of the map-edge distance ruler's major-tick numbers, Settings >
# Appearance. Only {settings.DISTANCE_TICK_FONT_PX_MIN}-{settings.DISTANCE_TICK_FONT_PX_MAX} are
# legal; anything else falls back to the default.
# Default: {settings.DISTANCE_TICK_FONT_PX_DEFAULT}.
distance_tick_font_px: {settings.DISTANCE_TICK_FONT_PX_DEFAULT}

# DEscape's own UI font, Settings > Appearance -- app chrome only (menus,
# dialogs, panels, the status log); the map view's overlay text keeps its
# own fixed sizes. "" means the platform default family.
ui_font_family: ""

# Point size for the same, {settings.UI_FONT_SIZE_MIN}-{settings.UI_FONT_SIZE_MAX}; anything else (or null) means
# the platform default size.
ui_font_size: null

# Every tool overlay color (Settings > Appearance), shown here at its
# default -- see settings.OVERLAY_COLORS for the full id/label/default list.
# RGB only, as "#rrggbb"; omit an entry to leave that element at its default.
overlay_colors:
{overlay_colors_block}

# Opacity of three overlay groups (Settings > Appearance), in percent: the
# Units selection (and its marquee), a selected map region, and the trigger
# overlay's areas. A multiplier on the whole group, on top of its colours;
# {settings.OVERLAY_OPACITY_MAX} is the original look. Only
# {settings.OVERLAY_OPACITY_MIN}-{settings.OVERLAY_OPACITY_MAX} are legal; anything else falls back to that
# group's default ({settings.OVERLAY_OPACITY_MAX}).
overlay_opacity:
{overlay_opacity_block}

# How the Triggers panel marks each trigger, condition and effect whose
# required fields are all set and whose references resolve (ok), or that is
# missing something (problem), Settings > Appearance > Trigger status. That is
# a completeness check, not a promise the trigger works in game. One of
# {_TRIGGER_STATUS_MARKERS}; anything else falls back to the default.
# Default: {settings.TRIGGER_STATUS_MARKER_DEFAULT}.
trigger_status_marker: {settings.TRIGGER_STATUS_MARKER_DEFAULT}

# Whether rows that pass are marked too. false leaves only problems marked:
# a row that passes gets no colour and no tick, in every marker mode.
# Default: true.
trigger_status_color_ok_rows: true

# The two marker colours, as "#rrggbb"; omit one to leave it at its default.
trigger_status_colors:
{trigger_status_colors_block}

# Settings > Saving. Autosave writes its own rotating recovery slot on a
# timer, never the file you have open, and never clears the unsaved-changes
# marker -- File > Recover from Autosave... is how you open one back up.
# Default: true.
autosave_enabled: true

# Minutes between autosave ticks. Only {_AUTOSAVE_INTERVALS} are legal;
# anything else falls back to the default. Default: {settings.AUTOSAVE_INTERVAL_DEFAULT}.
autosave_interval_min: {settings.AUTOSAVE_INTERVAL_DEFAULT}

# How many autosave slots to keep per document before the oldest is deleted.
# Only {_AUTOSAVE_RETENTIONS} are legal; anything else falls back to the
# default. Default: {settings.AUTOSAVE_RETENTION_DEFAULT}.
autosave_retention: {settings.AUTOSAVE_RETENTION_DEFAULT}

# Where autosave slots go: "central" (the autosave folder, autosave_dir
# below) or "sidecar" (beside the scenario itself). Sidecar falls back to
# the autosave folder for any document it cannot serve: an untitled one, a
# Steam Workshop/Proton path, or a shipped template. Default: "{settings.AUTOSAVE_LOCATION_DEFAULT}".
autosave_location: {settings.AUTOSAVE_LOCATION_DEFAULT}

# The autosave folder, as an absolute path. "" means the default, an
# autosave/ folder beside this config file, which also always holds the
# autosave index. A compatdata/ (Proton) path or a relative one is ignored.
# If the folder is missing when an autosave runs, that slot goes to the
# default folder instead; the folder is never created. Switching folders
# leaves existing autosaves where they are, still listed in Recover.
# Default: "".
autosave_dir: ""

# Whether a real save also writes the .bak (previous contents) and .orig
# (one-time pristine snapshot) pair beside the file. Default: true.
backups_enabled: true
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Validate without writing any files")
    args = parser.parse_args()

    current = render()
    if args.check:
        on_disk = OUT_PATH.read_text() if OUT_PATH.is_file() else None
        if on_disk != current:
            print(f"{OUT_PATH} is stale -- run tools/gen_config_example.py to regenerate", file=sys.stderr)
            return 1
        print(f"{OUT_PATH} is up to date")
        return 0

    OUT_PATH.write_text(current)
    print(f"Wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
