#!/usr/bin/env python3
"""Regenerates descape/cliff_connectivity.json: the Track B Stage 2 blocking
measurement from the 2026-09-02 cliffs plan -- a `neighbour-direction-set ->
(suffix, rotation candidates)` table for cliffs, measured from real scenario
placements (this is corpus geometry, not .dat content, so it belongs here
rather than in gen_unit_render_data.py).

**Install-free, corpus-scan tool** in the scan_wall_rotation.py mould:
`--scenario-dir` defaults to `examples/`, which ships zero cliff placements
(the public corpus has none), so a default run legitimately produces an
empty-but-valid table. The real table below was generated by pointing this
at a private, cliff-heavy corpus (287 scenario files, 22,894 cliff
placements) -- re-run it against any richer corpus to reproduce or update.

**Adjacency is tile-block, not centre-distance.** Two cliffs are neighbours
when their `render.unit_tile_bounds()` footprints share an edge (cardinal)
or touch at exactly one corner (diagonal) -- the same approach
`scan_wall_rotation.py`'s `_neighbour_mask` uses for walls, generalised from
4 directions to 8 since cliff footprints vary in size (3x3 down to 1x3) and
a centre-to-centre angle fragments one true relationship across several
octants when the two neighbours have different spans. Verified this isn't
the source of the low purity below: an earlier centre-distance-and-angle
measurement gave the same accuracy figures within 1%.

**The dirset key is over the FULL neighbour set, any suffix** -- a "vertical
run interior" node is one whose only neighbours are north and south,
regardless of what piece those neighbours are. `suffix` in the table's
values is the trailing digit of `object_catalog.object_name()` (e.g. "Cliff
(Default) 04" -> 4), which is stable across all ten families -- confirmed by
decoding real frames: rotation index N is the same shape (matching ink
bbox size and hotspot, within a few px) across Default/Desert/Snow/
Limestone/Terrace at N in {0, 1, 3, 6, 9, 13}, so pooling rotation data
across families is safe. Only the suffix (which of the family's 9 unit_consts
was placed) varies the footprint span; rotation alone selects the frame.

**Measured purity is well below the plan's informal ~80% estimate, and
that's a real finding, not a bug in this tool.** Two experiments (see the
2026-09-05 Track B Stage 2 execution notes in the plan) isolated why:

1. For any given dirset, TWO different suffixes are both common (e.g. the
   plain vertical-run dirset splits ~55%/45% between the 3x3 "01" piece and
   the 1x3 "02" piece) -- which SIZE of piece to use is a real stylistic
   choice human map-makers make, not something neighbour geometry
   determines. This, not the rotation/face axis, is the dominant source of
   unpredictability.
2. Within one suffix, the residual is genuinely the "face" pair the plan
   named: restricted to strict run-interior nodes (dirset exactly {N,S} or
   {E,W}, single suffix throughout), runs are constant-rotation ~34% of the
   time and cleanly period-2 alternating ~36% of the time -- ~70% combined
   "the observed rotation is one of exactly two acceptable values," which
   IS close to the plan's estimate once suffix choice is factored out.

So the table below picks the single most-common suffix per dirset (a
canonicalising choice a placement tool is allowed to make, unlike a corpus
classifier) and keeps the top-2 rotations as the value -- "top-2" because a
face is a real either-or, not noise to average away. Coverage is reported
per entry (`suffix_fraction`, `rotation_fraction`) so a consumer can see how
confident any given lookup is instead of trusting a single blended number.

**Each entry also carries `rotations_by_suffix`, and a consumer that pins
one piece size must read that, not the top-level `rotations`.** Added
2026-09-05 for Track B Stage 2's drag, which pins one suffix per run: the
top-level rotations are the MAJORITY suffix's, and rotation turns out to be
strongly conditioned on suffix, because a 1x3 footprint holds thin shapes
and a 3x3 holds big ones. A `{N, S}` run at suffix 1 uses rotation 1/2
(192px of decoded ink); the same dirset at suffix 2 uses 8/7 (90px). Mixing
them drew a run as a thin ridge between tall end caps. Purely additive --
a different projection of the same `scan()` output, so every field above
and every metadata figure is unchanged. Splitting by suffix makes the
buckets sparser, so a pair below `--min-suffix-n` is simply absent and the
consumer must fall back to its own manual value rather than borrow the
majority suffix's rotations.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from descape import cliff_catalog, unit_sprites
from descape.cliff_connectivity import adjacency_dir as _adjacency_dir
from descape.render import unit_tile_bounds
from descape.scenario_io import load_map_and_units

Bounds = tuple[int, int, int, int]
Direction = tuple[int, int]


def _corpus_files(scenario_dir: Path) -> list[Path]:
    return sorted(
        p
        for p in scenario_dir.iterdir()
        if p.suffix in (".aoe2scenario", ".scx2", ".scx", ".scn") or p.name == "play_Test"
    )


def _suffix_map() -> dict[int, int | None]:
    """unit_const -> the trailing digit of its object_catalog label (see
    module docstring for why this, not the raw unit_const, is the pooling
    key across families).

    The digit itself is read by `cliff_catalog.piece_suffix()` rather than
    by a regex kept here, so this table and the placement tool that consumes
    it can't drift apart on what a suffix is."""
    return {const: cliff_catalog.piece_suffix(const) for const in unit_sprites.cliff_consts()}


def scan(scenario_dirs: list[Path]) -> dict[frozenset[Direction], Counter[tuple[int, int]]]:
    """dirset -> Counter[(suffix, rotation)] across every cliff placement in
    every scenario file under `scenario_dirs`."""
    consts = unit_sprites.cliff_consts()
    suffix_of = _suffix_map()
    result: dict[frozenset[Direction], Counter[tuple[int, int]]] = defaultdict(Counter)

    for path in [p for d in scenario_dirs for p in _corpus_files(d)]:
        try:
            scenario = load_map_and_units(path)
        except Exception:  # noqa: BLE001 -- a scan tool, not production code
            continue
        mm = scenario.map_manager
        tile_w, tile_h = mm.map_width, mm.map_height

        nodes: list[tuple[int, float, Bounds]] = []
        for units in scenario.unit_manager.units:
            for unit in units:
                if unit.unit_const not in consts:
                    continue
                bounds = unit_tile_bounds(unit, tile_w, tile_h)
                if bounds is not None:
                    nodes.append((unit.unit_const, float(unit.rotation), bounds))

        for i, (const, rotation, bounds) in enumerate(nodes):
            dirset: set[Direction] = set()
            for j, (_, _, other_bounds) in enumerate(nodes):
                if i == j:
                    continue
                direction = _adjacency_dir(bounds, other_bounds)
                if direction is not None:
                    dirset.add(direction)
            suffix = suffix_of.get(const)
            if suffix is None:
                continue
            result[frozenset(dirset)][(suffix, int(rotation))] += 1

    return result


def build_table(
    dirset_to_result: dict[frozenset[Direction], Counter[tuple[int, int]]],
    min_n: int,
    min_suffix_n: int = 10,
) -> tuple[list[dict], dict]:
    total_all = sum(sum(c.values()) for c in dirset_to_result.values())
    entries = []
    covered_mass = 0
    covered_correct = 0

    for dirset, counter in sorted(dirset_to_result.items(), key=lambda kv: -sum(kv[1].values())):
        n = sum(counter.values())
        if n < min_n:
            continue
        by_suffix: dict[int, Counter[int]] = defaultdict(Counter)
        for (suffix, rotation), count in counter.items():
            by_suffix[suffix][rotation] += count
        top_suffix, suffix_n = max(
            ((s, sum(c.values())) for s, c in by_suffix.items()), key=lambda kv: kv[1]
        )
        top_rotations = [r for r, _ in by_suffix[top_suffix].most_common(2)]
        top_rotation_n = sum(c for r, c in by_suffix[top_suffix].items() if r in top_rotations)

        entries.append(
            {
                "dirset": sorted(list(d) for d in dirset),
                "suffix": top_suffix,
                "rotations": top_rotations,
                "n": n,
                "suffix_fraction": round(suffix_n / n, 4),
                "rotation_fraction": round(top_rotation_n / suffix_n, 4),
                # Rotation is strongly conditioned on suffix, and a consumer
                # that pins one piece SIZE for a whole run (Track B Stage 2's
                # drag, per the plan's Decisions addendum) needs the
                # rotations measured for THAT size, not for whichever size
                # happened to be this dirset's majority. Measured: a {N, S}
                # run at suffix 1 uses rotation 2 (192px of ink), the same
                # dirset at suffix 2 uses 8/7 (90px) -- a 1x3 footprint
                # holds thin shapes and a 3x3 holds big ones, so borrowing
                # across suffixes draws a wrong-scale piece. Additive: the
                # majority-suffix fields above are untouched, and this is a
                # different projection of the same scan, not new data.
                "rotations_by_suffix": {
                    str(suffix): {
                        "rotations": [r for r, _ in rotations.most_common(2)],
                        "n": sum(rotations.values()),
                    }
                    for suffix, rotations in sorted(by_suffix.items())
                    if sum(rotations.values()) >= min_suffix_n
                },
            }
        )
        covered_mass += n
        covered_correct += top_rotation_n

    metadata = {
        "total_records": total_all,
        "min_n": min_n,
        "min_suffix_n": min_suffix_n,
        "covered_records": covered_mass,
        "coverage": round(covered_mass / total_all, 4) if total_all else 0.0,
        "purity_within_coverage": round(covered_correct / covered_mass, 4) if covered_mass else 0.0,
        "purity_over_all_records": round(covered_correct / total_all, 4) if total_all else 0.0,
    }
    return entries, metadata


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--scenario-dir",
        type=Path,
        action="append",
        default=None,
        help="May be repeated to pool several corpora; defaults to examples/ alone",
    )
    parser.add_argument("--min-n", type=int, default=30, help="Minimum record count to pin a dirset entry")
    parser.add_argument(
        "--min-suffix-n",
        type=int,
        default=10,
        help="Minimum record count to pin one (dirset, suffix) pair's own rotations. Lower than "
        "--min-n because splitting by suffix makes every bucket sparser; a pair below it is simply "
        "absent, and a consumer must fall back rather than borrow another suffix's rotations",
    )
    parser.add_argument(
        "--output", type=Path, default=Path(__file__).resolve().parent.parent / "descape" / "cliff_connectivity.json"
    )
    args = parser.parse_args()

    scenario_dirs = args.scenario_dir or [Path(__file__).resolve().parent.parent / "examples"]
    for scenario_dir in scenario_dirs:
        if not scenario_dir.is_dir():
            print(f"No such scenario directory: {scenario_dir}", file=sys.stderr)
            sys.exit(1)

    dirset_to_result = scan(scenario_dirs)
    entries, metadata = build_table(dirset_to_result, args.min_n, args.min_suffix_n)

    args.output.write_text(
        json.dumps(
            {
                "_comment": "Cliff neighbour-direction-set -> (suffix, rotation candidates) -- see tools/gen_cliff_connectivity.py",
                "metadata": metadata,
                "entries": entries,
            },
            indent=2,
        )
        + "\n"
    )

    print(f"Scanned {scenario_dirs}: {metadata['total_records']} cliff records")
    print(f"Pinned {len(entries)} dirsets at n >= {args.min_n}, covering {metadata['coverage']:.1%} of records")
    print(
        f"Purity within that coverage: {metadata['purity_within_coverage']:.1%} "
        f"({metadata['purity_over_all_records']:.1%} of all records)"
    )
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
