#!/usr/bin/env python3
"""Regenerates config.example.yaml from descape/settings.py and
descape/asset_source.py, so the example file can't silently drift out of
sync with the real config schema the way it had (missing dark_mode/
window_size, missing 16 of 22 keybind entries, one dead tool_pencil key
left over from before the tools list was restructured -- none of that
caught until someone happened to compare them by hand).

    python3 tools/gen_config_example.py          # write config.example.yaml
    python3 tools/gen_config_example.py --check  # exit 1 if it's stale

tests/test_config_example.py runs the --check equivalent as part of the
default pytest tier, so a settings.py change that isn't matched here fails
the normal test run, not just a hand pass.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from descape import asset_source, edge_ticks, iso_geometry, settings  # noqa: E402

OUT_PATH = ROOT / "config.example.yaml"

_QUALITY_LABELS = ", ".join(f"{n}={label}" for n, label in sorted(settings.GRAPHICS_QUALITY_LABELS.items()))

_ELEV_STEP_STOP_COUNT = len(settings.ELEV_STEP_PCT_STOPS)

_TICK_INTERVALS = " or ".join(str(n) for n in edge_ticks.TICK_INTERVALS)


def render() -> str:
    keybinds_yaml = yaml.safe_dump(
        {action_id: default for action_id, _label, default in settings.REBINDABLE_ACTIONS},
        default_flow_style=False,
        sort_keys=False,
    )
    keybinds_block = "\n".join(f"  {line}" for line in keybinds_yaml.splitlines())

    overlay_colors_yaml = yaml.safe_dump(
        {color_id: default for color_id, _label, default in settings.OVERLAY_COLORS},
        default_flow_style=False,
        sort_keys=False,
    )
    overlay_colors_block = "\n".join(f"  {line}" for line in overlay_colors_yaml.splitlines())

    return f"""\
# Example config.yaml -- copy this file to config.yaml in your OS's
# DEscape config directory and edit (Linux: $XDG_CONFIG_HOME/DEscape/ or
# ~/.config/DEscape/; macOS: ~/Library/Application Support/DEscape/;
# Windows: %APPDATA%\\DEscape\\). Every key below is optional; an omitted
# key falls back to the default noted in its comment. Generated by
# tools/gen_config_example.py
# from descape/settings.py and descape/asset_source.py -- run that script
# after changing either, rather than hand-editing this file (also gated by
# tests/test_config_example.py, so a mismatch fails the default test tier).

# Path to your AoE2:DE install (steamapps/common/AoE2DE or similar).
# Enables real per-tile terrain textures instead of averaged flat colors.
# Also settable via the AOE2DE_INSTALL_PATH env var or the viewer's own
# Load button -- see asset_source.py's module docstring for priority order.
# No default: falls back to flat colors if unset everywhere.
aoe2de_install: /path/to/steamapps/common/AoE2DE

# Language folder under the install's resources/ (e.g. de, fr, es) that
# trigger reference pickers resolve real object/tech display names from --
# see object_catalog.py's resolve_name(). Only takes effect with
# aoe2de_install also set; falls back to the ALL-CAPS library name otherwise.
# Default: "{asset_source.DEFAULT_LANGUAGE}".
language: {asset_source.DEFAULT_LANGUAGE}

# 1-4 ({_QUALITY_LABELS}), see settings.GRAPHICS_QUALITY_LABELS.
# Default: {settings.GRAPHICS_QUALITY_DEFAULT}.
graphics_quality: {settings.GRAPHICS_QUALITY_DEFAULT}

# Stepped elevation height, percent of half_h. Only the {_ELEV_STEP_STOP_COUNT} stops
# {settings.ELEV_STEP_PCT_MIN}-{settings.ELEV_STEP_PCT_MAX} in steps of {settings.ELEV_STEP_PCT_STEP} are legal; anything else snaps to the
# nearest one on read, see settings.ELEV_STEP_PCT_STOPS.
# Default: {iso_geometry.ELEV_STEP_DEFAULT_PCT}.
elev_step_pct: {iso_geometry.ELEV_STEP_DEFAULT_PCT}

# Anchor mouse-wheel zoom under the cursor (true) or the view center
# (false). Default: true.
zoom_centered_on_cursor: true

# Dark app-chrome theme, Settings > Appearance. Default: false.
dark_mode: false

# After a file opens, warm the neighbouring zoom levels' unit sprites in
# idle time so the first zoom doesn't stutter, Settings > Appearance.
# Costs a few seconds of background work per open and some memory; never
# blocks the window. Default: true.
preload_zoom_levels: true

# Ruler-style distance ticks in the void just outside the map border,
# View > Distance Ticks. Default: false.
distance_ticks: false

# Tiles between adjacent minor ticks. Only {_TICK_INTERVALS} are legal; anything
# else falls back to the default on read, see edge_ticks.TICK_INTERVALS.
# Every {edge_ticks.MAJORS_PER_MINOR}th minor is a major and carries a tile number.
# Default: {edge_ticks.TICK_INTERVAL_DEFAULT}.
distance_tick_interval: {edge_ticks.TICK_INTERVAL_DEFAULT}

# Main window size in pixels, [width, height]. Persisted automatically on
# resize -- not something you normally set by hand.
# Default: [{settings.DEFAULT_WINDOW_WIDTH}, {settings.DEFAULT_WINDOW_HEIGHT}].
window_size: [{settings.DEFAULT_WINDOW_WIDTH}, {settings.DEFAULT_WINDOW_HEIGHT}]

# Width in pixels of the left info/trigger panel and the map view,
# [left, right]. Persisted automatically when you drag the split -- not
# something you normally set by hand. Omitted entirely until first saved.
# split_sizes: [340, 900]

# Height in pixels of the system log, below the map view. Persisted
# automatically when you drag the split -- not something you normally set by
# hand. Omitted entirely until first saved; until then the log is four text
# lines tall, so unlike split_sizes above there is no fixed default to quote
# here -- it depends on your font. The value below is only an example.
# log_height: 120

# Every rebindable action (Settings > Keybinds), shown here at its default
# -- see settings.REBINDABLE_ACTIONS for the full id/label/default list.
# Omit an entry to leave that action at its default; "" means unbound.
keybinds:
{keybinds_block}

# Pixel size of the Ruler's on-map measurement label, Settings > Appearance.
# Only {settings.RULER_LABEL_FONT_PX_MIN}-{settings.RULER_LABEL_FONT_PX_MAX} are legal; anything else falls back to the default.
# Default: {settings.RULER_LABEL_FONT_PX_DEFAULT}.
ruler_label_font_px: {settings.RULER_LABEL_FONT_PX_DEFAULT}

# Pixel size of the map-edge distance ruler's major-tick numbers, Settings >
# Appearance. Only {settings.DISTANCE_TICK_FONT_PX_MIN}-{settings.DISTANCE_TICK_FONT_PX_MAX} are legal; anything else falls back to the default.
# Default: {settings.DISTANCE_TICK_FONT_PX_DEFAULT}.
distance_tick_font_px: {settings.DISTANCE_TICK_FONT_PX_DEFAULT}

# Every tool overlay color (Settings > Appearance), shown here at its
# default -- see settings.OVERLAY_COLORS for the full id/label/default list.
# RGB only, as "#rrggbb"; omit an entry to leave that element at its default.
overlay_colors:
{overlay_colors_block}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Validate without writing any files")
    args = parser.parse_args()

    current = render()
    if args.check:
        on_disk = OUT_PATH.read_text() if OUT_PATH.is_file() else None
        if on_disk != current:
            print(f"{OUT_PATH} is stale -- run tools/gen_config_example.py to regenerate", file=sys.stderr)
            return 1
        print(f"{OUT_PATH} is up to date")
        return 0

    OUT_PATH.write_text(current)
    print(f"Wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
