"""Track B Stage 2 blocking measurement (2026-09-02 cliffs plan): a
`neighbour-direction-set -> (suffix, rotation candidates)` lookup for
auto-connecting cliff placement, plus the tile-adjacency primitive it's
built from.

The pinned table in `cliff_connectivity.json` is generated by
`tools/gen_cliff_connectivity.py` from a real scenario corpus -- see that
tool's module docstring for the adjacency definition, the family-pooling
justification, and why measured purity (61% within the pinned dirsets, 58%
over every cliff record) lands well below the plan's own informal ~80%
estimate. In short: which SIZE of piece (suffix) to use for a given
neighbour shape is a real stylistic choice map-makers make and isn't
determined by geometry -- that's the dominant source of unpredictability,
not the rotation/"face" axis the plan named. This table canonicalises on
the single most common suffix per dirset (a placement tool, unlike a corpus
classifier, is allowed to pick one) and keeps the top-2 observed rotations
as candidates, since a face is a real either-or rather than noise.

Not consumed by any write path yet -- Stage 2's drag tool (which face to
pick when both candidates are legal, how to resolve a dirset with no pinned
entry) is unbuilt UI work the blocking measurement was a prerequisite for,
not a part of it.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

Direction = tuple[int, int]

_TABLE_PATH = Path(__file__).resolve().parent / "cliff_connectivity.json"


@lru_cache(maxsize=1)
def _data() -> dict:
    return json.loads(_TABLE_PATH.read_text())


def metadata() -> dict:
    """The generator's own coverage/purity report for the pinned table --
    see tools/gen_cliff_connectivity.py's docstring for what each field
    means and why the purity figures are lower than the plan first guessed."""
    return _data()["metadata"]


@lru_cache(maxsize=1)
def _table() -> dict[frozenset[Direction], tuple[int, tuple[int, ...]]]:
    table: dict[frozenset[Direction], tuple[int, tuple[int, ...]]] = {}
    for entry in _data()["entries"]:
        dirset = frozenset(tuple(d) for d in entry["dirset"])
        table[dirset] = (entry["suffix"], tuple(entry["rotations"]))
    return table


def resolve(dirset: frozenset[Direction]) -> tuple[int, tuple[int, ...]] | None:
    """(suffix, rotation candidates) for an exact neighbour-direction-set
    match, or None if this dirset wasn't common enough in the measured
    corpus to pin (see metadata()["min_n"]) -- a caller needs its own
    fallback for the unpinned ~5% of shapes, not provided here.

    The rotations here are the MAJORITY SUFFIX's. A caller that pins one
    piece size for a whole run wants rotations_for() below instead; see its
    docstring for the measurement that makes the difference visible."""
    return _table().get(dirset)


@lru_cache(maxsize=1)
def _by_suffix() -> dict[tuple[frozenset[Direction], int], tuple[int, ...]]:
    table: dict[tuple[frozenset[Direction], int], tuple[int, ...]] = {}
    for entry in _data()["entries"]:
        dirset = frozenset(tuple(d) for d in entry["dirset"])
        for suffix, value in entry.get("rotations_by_suffix", {}).items():
            table[(dirset, int(suffix))] = tuple(value["rotations"])
    return table


def rotations_for(dirset: frozenset[Direction], suffix: int) -> tuple[int, ...] | None:
    """Rotation candidates measured for this neighbour shape AT THIS PIECE
    SIZE, or None if that pair was too rare to pin (metadata()["min_suffix_n"]).

    Rotation is strongly conditioned on suffix and the two must not be
    mixed: a {N, S} run at suffix 1 uses rotation 2 (192px of ink), the
    same dirset at suffix 2 uses 8/7 (90px) -- a 1x3 footprint holds thin
    shapes and a 3x3 holds big ones. Borrowing resolve()'s majority-suffix
    rotations for a different suffix draws a wrong-scale piece, which is
    exactly what made a straight run render as a thin line between tall end
    caps. A caller must fall back to its own manual value on None rather
    than to resolve(), or it reintroduces that bug silently."""
    return _by_suffix().get((dirset, suffix))


def adjacency_dir(a: tuple[int, int, int, int], b: tuple[int, int, int, int]) -> Direction | None:
    """8-direction tile-block adjacency between two `render.unit_tile_bounds()`
    boxes (half-open (x0, x1, y0, y1)), or None if they don't touch.
    Cardinal directions require a shared edge; diagonals require the boxes
    to meet at exactly one shared corner point. Tile-block, not
    centre-to-centre distance/angle, because cliff footprints range from
    1x3 to 3x3 -- see tools/gen_cliff_connectivity.py's module docstring."""
    ax0, ax1, ay0, ay1 = a
    bx0, bx1, by0, by1 = b
    x_overlap = ax0 < bx1 and bx0 < ax1
    y_overlap = ay0 < by1 and by0 < ay1
    if x_overlap and ay1 == by0:
        return (0, 1)
    if x_overlap and ay0 == by1:
        return (0, -1)
    if y_overlap and ax1 == bx0:
        return (1, 0)
    if y_overlap and ax0 == bx1:
        return (-1, 0)
    if ax1 == bx0 and ay1 == by0:
        return (1, 1)
    if ax1 == bx0 and ay0 == by1:
        return (1, -1)
    if ax0 == bx1 and ay1 == by0:
        return (-1, 1)
    if ax0 == bx1 and ay0 == by1:
        return (-1, -1)
    return None
