"""Qt-free rules for what a building (or a transport) can hold inside it:
capacity, and which objects the game would let you garrison there.

Leaf module -- no Qt, no genieutils. `descape/garrison_table.json` (committed,
generated by tools/gen_garrison_table.py) is a factual table extracted from
the game's own unit data, not asset content, same standing as
`unit_stats.json`. Lazy and `lru_cache`d, so a document that never opens the
Inspector's garrison block never pays the parse.

**The host side is data, the occupant side is a measured mapping.**
`garrison_type` is a bitfield the .dat carries per host; the occupant side is
the unit's `class_`, and the engine's class-to-bit rule is nowhere in the
file. _CLASS_BIT below is that rule, derived from what the shipped .dat's own
masks have to mean:

- A Watch Tower (79) and a Town Center (109) both carry 11 (1|2|8), and the
  corpus garrisons Archers (class 0) in towers and Villagers (class 4) in
  Town Centers -- so bit 1 is the villager bit and bit 2 covers foot soldiers
  including foot archers, not class 6 alone.
- A Castle (82) carries 15, adding bit 4 over the tower's mask: mounted units,
  which a castle takes and a tower does not.
- A Dock (45) carries 64 on its own, and a dock holds ships and nothing else.
- Bit 8 is the remaining bit in the tower/TC mask, and monks are the remaining
  thing a tower holds.
- No shipped host sets bits 16 or 32, so herdables and siege map to bits
  nothing admits -- which is the right answer for a building (no building in
  the game garrisons a mangonel), and transports are handled below instead.

A host with `garrison_capacity > 0` and no `building` section at all (a
Transport Ship, a ram, a siege tower) has no mask to read. Those take
_LAND_MASK: every land bit, which is what a transport carries in game. It
over-accepts for a ram (infantry only in game); the refusal this module backs
exists to stop an impossible file, and an over-refusal would block a legal
edit, so the bias is deliberate.

Capacity is the .dat's base value. Civ bonuses and techs raise it at runtime
and are not in this table, so `capacity()` is strict by design -- the UI names
the base number when it refuses.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_TABLE_JSON_PATH = Path(__file__).resolve().parent / "garrison_table.json"

# Host-side garrison_type bits. Named for what the shipped masks show them to
# mean (see the module docstring), not guessed from a wiki.
VILLAGER_BIT = 1
FOOT_BIT = 2
MOUNTED_BIT = 4
MONK_BIT = 8
HERDABLE_BIT = 16
SIEGE_BIT = 32
SHIP_BIT = 64

# What a host with capacity but no `building` section admits: everything that
# walks. Transports carry siege; nothing carries a herd onto a boat.
_LAND_MASK = VILLAGER_BIT | FOOT_BIT | MOUNTED_BIT | MONK_BIT | SIEGE_BIT

# Unit.class_ -> the single garrison bit that class answers to. A class absent
# here can never be garrisoned anywhere (buildings, walls, trees, resources,
# projectiles, rubble): no mask bit selects it.
_CLASS_BIT = {
    0: FOOT_BIT,  # Archer -- foot archers ride the infantry bit (corpus: tower 79)
    4: VILLAGER_BIT,  # Civilian (corpus: town centre 109)
    6: FOOT_BIT,  # Infantry
    13: SIEGE_BIT,  # Siege Weapon
    18: MONK_BIT,  # Priest
    12: MOUNTED_BIT,  # Cavalry
    19: MOUNTED_BIT,  # Trade Cart
    2: SHIP_BIT,  # Trade Boat
    20: SHIP_BIT,  # Transport Boat
    21: SHIP_BIT,  # Fishing Boat
    22: SHIP_BIT,  # Warship
    23: MOUNTED_BIT,  # Conquistador and the other mounted gunpowder heroes
    28: FOOT_BIT,  # War dog
    35: FOOT_BIT,  # Petard
    36: MOUNTED_BIT,  # Cavalry Archer
    43: MONK_BIT,  # Monk carrying a relic
    44: FOOT_BIT,  # Hand Cannoneer
    47: MOUNTED_BIT,  # Scout (corpus: transport 545)
    51: SIEGE_BIT,  # Packed siege (packed trebuchet, packed Turtle Ship)
    53: SHIP_BIT,  # Boarding boat
    54: SIEGE_BIT,  # Unpacked siege
    55: SIEGE_BIT,  # Siege wagons and ballistae
    56: FOOT_BIT,  # Foot raider (campaign RFARC/RFSWD)
    57: MOUNTED_BIT,  # Cavalry raider (campaign RCARC/RCSWD)
    58: HERDABLE_BIT,  # Livestock
    59: FOOT_BIT,  # King
    61: MOUNTED_BIT,  # Controlled animal (a riderless horse or camel)
}


@lru_cache(maxsize=1)
def _table() -> tuple[dict[int, dict[str, int]], dict[int, int]]:
    data = json.loads(_TABLE_JSON_PATH.read_text())
    hosts = {int(const): entry for const, entry in data["hosts"].items()}
    classes = {int(const): value for const, value in data["classes"].items()}
    return hosts, classes


def capacity(host_const: int) -> int:
    """How many units `host_const` holds, base game, or 0 -- which is also
    the answer for a const the table has never heard of."""
    hosts, _ = _table()
    entry = hosts.get(host_const)
    return entry["cap"] if entry else 0


def garrison_mask(host_const: int) -> int:
    """The host's garrison_type bitfield, or _LAND_MASK for a host that has
    capacity but no `building` section (a transport, a ram). 0 for anything
    that holds nothing at all."""
    hosts, _ = _table()
    entry = hosts.get(host_const)
    if not entry:
        return 0
    return entry.get("type", _LAND_MASK)


def can_hold(host_const: int) -> bool:
    """Whether this const is a garrison host worth showing a block for:
    capacity AND a mask that admits something.

    The two questions come apart on 35 shipped consts -- a Market, a Barracks
    and a Stable all carry `garrison_capacity` 10 with mask 0, which is the
    .dat's way of saying "no". Capacity alone would put an Inspector block
    with a permanently disabled Add button on a third of the buildings in the
    game.
    """
    return capacity(host_const) > 0 and garrison_mask(host_const) != 0


def unit_bit(unit_const: int) -> int:
    """The garrison bit `unit_const`'s class answers to, or 0 for a const
    that can never be garrisoned."""
    _, classes = _table()
    return _CLASS_BIT.get(classes.get(unit_const, -1), 0)


def accepts(host_const: int, occupant_const: int) -> bool:
    """Whether the game would let `occupant_const` garrison inside
    `host_const`. Capacity is a separate question -- see capacity()."""
    return bool(garrison_mask(host_const) & unit_bit(occupant_const))


@lru_cache(maxsize=32)
def eligible_consts(host_const: int) -> frozenset[int]:
    """Every const `host_const` admits. Cached per host: the Add… picker
    rebuilds its item list every time it opens, and this is a walk of all
    2,642 table rows."""
    mask = garrison_mask(host_const)
    if not mask:
        return frozenset()
    _, classes = _table()
    return frozenset(const for const, class_ in classes.items() if mask & _CLASS_BIT.get(class_, 0))
