"""Qt-free lookup of a unit_const's base in-game stats (hit points, attack,
melee armour, pierce armour, range), backing the Inspector's `Base stats`
section.

Leaf module -- no Qt, no genieutils. `descape/unit_stats.json` (committed,
generated by tools/gen_unit_stats.py) is a factual table extracted from the
game's own unit data, not asset content. Lazy and `lru_cache`d so importing
this module -- or opening a document that never enters Units mode -- never
pays the parse cost.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_STATS_JSON_PATH = Path(__file__).resolve().parent / "unit_stats.json"


@lru_cache(maxsize=1)
def _stats_table() -> dict[int, dict[str, float]]:
    data = json.loads(_STATS_JSON_PATH.read_text())
    return {int(uid): entry for uid, entry in data["stats"].items()}


def unit_stats(unit_const: int) -> dict[str, float]:
    """Base stats for unit_const, or {} when the table has no entry -- an
    unrecognized const (e.g. from a modded scenario) or a const with no
    positive HP and no combat block, same as a tree."""
    return _stats_table().get(unit_const, {})
