"""Resolves a unit to its real in-game sprite: unit_const -> .sld frame -> a
tinted, scaled RGBA array the Stepped compositor can paste.

Leaf module. numpy and stdlib only -- no Qt, no genieutils, and nothing here
reaches into descape/render.py.

**No game assets are shipped.** Pixels are read from the user's own configured
AoE2:DE install at runtime, the same posture asset_source.py takes for terrain
textures. descape/unit_graphic_map.json (committed, generated by
tools/gen_unit_graphic_map.py) is a factual data table extracted from the
game's unit and graphic tables, not asset content.

Everything below falls back to None rather than raising. A caller that gets
None draws today's coloured mark, so an absent install, an absent file, an
unreadable file and an undecodable frame are all exactly as safe as "no install
configured" already is.

## How a unit becomes a frame

A graphic's frames are stored **angle-major**: `frames[angle * frame_count]` is
that angle's first (standing) pose, which is the only one a scenario editor
needs -- there is no animation loop here. `angle_count` is the number of angles
actually stored; `mirroring_mode` does NOT halve it, despite the usual AoE2
convention (measured over 400 graphics: total_frames - angle_count*frame_count
is 0 or 1, never half, and a graphic's stored frames are pixel-distinct rather
than mirrored duplicates). Animated graphics carry one extra frame at the END,
so no index offset is needed.

## How player colour is applied

The MAIN layer renders the player-coloured region in near-grey, and the
PLAYERCOLOR layer is a per-pixel COVERAGE mask (its interior sits at 255, its
boundary ramps -- it is antialiasing, not a shade index). The tint is a plain
multiply by one RGB per player:

    out = lerp(main, main * team_rgb, coverage)

TEAM_COLORS below are the game's own, read from its
resources/_common/palettes/spritecolors.json. The 256-entry playercolor_*.pal
files are the legacy SLP path and must NOT be used here: their entries 128..255
are all black, while MAIN's luminance under the mask reaches 247, so indexing
them by luminance paints most sprites black.
"""

from __future__ import annotations

import json
import math
from collections import OrderedDict
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import numpy as np

from descape import asset_source, debug_log
from descape.sld_decoder import SLDError, load_sld

GRAPHIC_MAP_PATH = Path(__file__).resolve().parent / "unit_graphic_map.json"
GRAPHICS_SUBPATH = "resources/_common/drs/graphics"

# DE's own iso tile diamond width for x1 assets. Measured against the spans the
# game's unit table reports, not read off a wiki: a building sprite's ink
# extends symmetrically about its hotspot by span * 96 / 2 in x and reaches
# span * 96 / 4 below it in y (House 2x2 -84..+79 vs +-96; Barracks 3x3
# -148..+140 vs +-144; Wonder 5x5 -249..+248 vs +-240).
NATIVE_TILE_W = 96

# How far the farthest sprite's pixels reach past its own hotspot, per side, in
# the same native px NATIVE_TILE_W is in -- so a canvas-pixel padding is
# reach * sprite_scale(half_w). descape/render.py's _sprite_reach_px is the only
# consumer: it turns these into the per-side widening an edit's dirty bbox needs
# so a sprite standing on a dirty tile cannot escape it and leave a stale
# fragment behind.
#
# Measured by tools/scan_sprite_reach.py over every .sld descape/
# unit_graphic_map.json references, from each frame's MAIN-layer header box
# (which bounds the ink bbox _cropped_to_ink produces). The worst file is named
# per direction so a re-scan after a game patch either reproduces the number or
# says which graphic grew. UP dominates by a wide margin -- wonders and
# cathedrals out-reach every horizontal case by 50%.
MAX_SPRITE_REACH_LEFT = 404   # b_scen_cathedral_rubble_x1
MAX_SPRITE_REACH_RIGHT = 424  # b_scen_cathedral_rubble_x1
MAX_SPRITE_REACH_UP = 650     # b_west_wonder_britons_x1
MAX_SPRITE_REACH_DOWN = 200   # b_scen_colosseum_x1

# How far the stored angle set is rotated from the scenario's own `rotation`
# field, in degrees, and which way the index walks as rotation increases.
#
# **The offset is ANGULAR, not an index offset, and that distinction is the
# whole reason this constant is in degrees.** Index 0 is a fixed compass
# direction for every graphic regardless of how many angles it stores, so a
# correction of "45 degrees" is 1 step for an angle_count of 8 but 2 for 16 and
# 4 for 32. angle_count is nowhere near uniform -- measured over the 2,439
# graphics unit_graphic_map.json references, 16 dominates at 1,163 and 8 is
# rare at 76, with everything from 2 to 72 present. An index-space constant
# (which this was until 2026-08-24) therefore cannot express a fixed angular
# correction at all: it would rotate most units by 22.5 degrees while rotating
# a handful by 45.
#
# The magnitude comes from a live-window observation: units rendered 45 degrees
# to the RIGHT of where the real editor puts them, uniformly. Uniformly is the
# load-bearing word -- a wrong ANGLE_DIRECTION would MIRROR the facing about an
# axis, so the error would vary with rotation instead of being constant. That
# it is constant is what says the direction is already right and only the zero
# point was off.
#
# **The sign is -45, confirmed against the running game, and it is worth
# knowing WHY it is not +45.** Correcting a "units face 45 degrees too far
# right" error means adding 45 degrees if the game's `rotation` grows
# counter-clockwise and subtracting it if clockwise. Nothing in the .sld, the
# .dat or openage states which, so +45 was tried first on the reasoning that a
# radians field usually follows the maths convention. That put units 90 degrees
# out -- the signature of a sign error, being exactly twice the offset -- so
# **AoE2's rotation field grows CLOCKWISE on screen.** Recorded here because it
# cost a round trip to a human with the game open, and nothing else in this
# codebase pins it.
ANGLE_ZERO_OFFSET_DEG = -45.0
ANGLE_DIRECTION = 1

# resources/_common/palettes/spritecolors.json's TeamColors block, as RGB.
# Index is the scenario's own player id: 0 is GAIA, 1..8 the real players.
# GAIA's (255, 255, 255) multiplies to identity, so a GAIA unit needs no
# special case anywhere.
TEAM_COLORS = (
    (255, 255, 255),  # GAIA
    (0, 0, 255),
    (255, 0, 0),
    (0, 169, 27),
    (214, 214, 27),
    (123, 239, 240),
    (138, 19, 247),
    (102, 102, 102),
    (255, 146, 5),
)

# Sized by tools/bench_unit_sprites.py (P3-g4), not guessed. Both matter
# because sld_decoder holds no cache of its own and a delta chain can be 313
# links deep, so one wanted frame can pay for hundreds of predecessor decodes.
#
# **The failure mode these avoid is a cache that silently does nothing.** At
# the first-pass 256, the worst real file (old-allies-final-v2, 652 distinct
# (file, frame) pairs before the per-player and per-mip-level multiplier) ran
# a WARM layer rebuild in 4562ms against a 4768ms cold one -- every entry was
# evicted before it could be reused, so the cache cost memory and bought
# nothing. It is not enough for a capacity to be "big"; it has to exceed a
# real file's distinct-key count, or it is worse than no cache at all.
#
# Entry counts rather than a byte budget, because cropping to the ink bbox
# made entries small and predictable: measured across the three biggest
# example files, a scaled entry averages ~19KB and a native one ~200KB. So
# these caps are roughly 40MB scaled and 50MB native at worst, and typically a
# small fraction of that.
NATIVE_CACHE_SIZE = 256
SCALED_CACHE_SIZE = 2048


@dataclass(frozen=True)
class SpriteDraw:
    """One unit's sprite, ready to paste.

    rgba is (h, w, 4) uint8 already tinted for its owner and already scaled for
    the caller's tile_px. hotspot_x/y are in that same scaled pixel space, and
    are the pixel that sits on the ground anchor -- see anchor_screen_pos().
    """

    rgba: np.ndarray
    hotspot_x: int
    hotspot_y: int


@dataclass(frozen=True)
class SpritePiece:
    """One piece of a composite building's sprite (a town centre's back/main/
    center/front, a pasture's corner posts), ready to paste at an offset from
    the unit's own anchor. dx/dy are in the same scaled canvas-pixel space as
    SpriteDraw's hotspot -- see sprite_pieces_for()."""

    draw: SpriteDraw
    dx: int
    dy: int


class _LRU(OrderedDict):
    """Smallest thing that is actually an LRU. functools.lru_cache can't be
    used for the scaled cache: its capacity has to stay adjustable from
    P3-g4's bench without redecorating a module-level function."""

    def __init__(self, capacity: int):
        super().__init__()
        self.capacity = capacity

    def get_or_none(self, key):
        if key in self:
            self.move_to_end(key)
            return self[key]
        return None

    def put(self, key, value):
        self[key] = value
        self.move_to_end(key)
        while len(self) > self.capacity:
            self.popitem(last=False)


_native_cache = _LRU(NATIVE_CACHE_SIZE)
_scaled_cache = _LRU(SCALED_CACHE_SIZE)

# Cached in place of a sprite when a key resolves to nothing.
#
# **Caching the negative result is not an optimization, it is the difference
# between a working cache and a broken one.** A unit that resolves nowhere --
# no file on this install, a frame index past the file's end -- costs a full
# SLDFile walk to discover that, every single time.
# Measured on the 32,272-unit corpus outlier before this existed: a WARM layer
# rebuild spent 1.59s of its 1.74s inside SLDFile.__init__, re-walking files
# 641 times to re-derive answers it already had. Only ~1% of that file's units
# are unresolvable; they were most of its cost.
_MISS = object()


def clear_caches() -> None:
    """Drops both LRUs. For tests, and for a settings change that repoints the
    install path -- a cached array outlives the file it came from otherwise."""
    _native_cache.clear()
    _scaled_cache.clear()


@lru_cache(maxsize=1)
def graphic_map() -> dict[int, dict]:
    """unit_const -> {graphic_id, file_name, angle_count, mirroring_mode,
    frame_count}, from the committed table."""
    data = json.loads(GRAPHIC_MAP_PATH.read_text())["graphics"]
    return {int(k): v for k, v in data.items()}


def angle_index(rotation: float, angle_count: int) -> int:
    """Which stored angle a rotation (radians) selects.

    Real rotations are NOT quantized -- across the example corpus 20,122
    non-GAIA units carry 34 distinct values, mixing exact 16-grid points with
    hand-typed round numbers, 40% of them 0.0, and ~4% outside [0, 2*pi)
    entirely (7.0 appears 574 times). So this rounds and wraps rather than
    looking anything up.

    GAIA is the caller's problem, not this function's: a GAIA object's
    `rotation` is a doodad graphic-variant index, not an angle (see AGENTS.md's
    hard rule), so it must never be passed here.
    """
    if angle_count <= 1:
        return 0
    steps = rotation / (2 * math.pi) * angle_count
    # ANGLE_ZERO_OFFSET_DEG is converted into THIS graphic's own step size --
    # see its comment for why a fixed index offset cannot do this job. Kept
    # outside the ANGLE_DIRECTION product deliberately: direction is how the
    # index walks as rotation grows, the offset is a fixed rotation of the
    # whole set, and multiplying the two would silently flip the correction if
    # the direction were ever changed.
    # The offset applies ONLY when it lands on a whole stored step -- i.e. when
    # angle_count is a multiple of 8, since the offset is 45 degrees. That is
    # what the offset MEANS, not a special case for any one graphic: a
    # zero-point correction rotates which stored angle a rotation selects, so
    # if it does not map stored angles onto stored angles then the graphic's
    # angle set is not a 45-degree-compatible sampling of the circle, and there
    # is no sense in which it is "45 degrees out". It fires for every
    # angle_count that is not a multiple of 8, and 3, 6, 7, 9 and more are all
    # in real use.
    #
    # Walls are the case that motivated writing it down. They store 5 angles,
    # where 45 degrees is 0.625 of a step, so applying the offset re-quantized
    # every facing to a neighbour and moved walls a full 72-degree frame
    # (reported from a live window 2026-08-24, the same session the offset was
    # added for units). Walls no longer reach this function at all -- their
    # frames are shape variants rather than facings, so _rotation_is_variant()
    # diverts them to variant_index() -- but the skip above is general and
    # stays.
    offset_steps = ANGLE_ZERO_OFFSET_DEG / 360.0 * angle_count
    if offset_steps != int(offset_steps):
        offset_steps = 0.0
    # Rounds the SUM, not each term: the offset is exact only when angle_count
    # is a multiple of 8 (16 -> 2.0, 8 -> 1.0), and 25 -> 3.125 is a real case.
    # Rounding once is rounding the final angle, which is the quantity that has
    # to land on a stored frame.
    #
    # floor(x + 0.5), not round(): round() is banker's rounding, which breaks
    # exact .5 ties toward EVEN and so breaks them inconsistently. That only
    # became reachable once the offset could be fractional -- at angle_count 4
    # a 45-degree offset is exactly half a step, and banker's rounding then
    # sent rotations 0 and pi/2 to the same stored angle while pi and 3pi/2
    # went to different ones. Half-up is arbitrary too, but uniformly so, which
    # is what keeps distinct facings distinct.
    return math.floor(ANGLE_DIRECTION * steps + offset_steps + 0.5) % angle_count


# Confirmed 2026-08-25: these
# unit_consts' stored frames are shape variants (wall run/tower/column/etc.),
# not facings, so their `rotation` field must go through variant_index()
# rather than angle_index(). 117 by direct frame decode. 72/119/788 share one
# file_name (b_dark_wall_palisade_flag_x1) among THEMSELVES, not with 117, so
# they must share its behaviour regardless of class. 155
# (b_west_wall_fortified_x1) shows the same mixed integer/exact-k*2pi/5-radian
# rotation pattern as 117 and 72, i.e. the same real Wall family.
#
# 370/1062/2678 (City Wall, Fence, scenario Fortified Wall) rest only on that
# plan's rotation-value corpus profiling -- integer-only, never the wide
# hand-typed spread angle_index()'s own docstring measures for genuine facing
# graphics. Weaker evidence than a direct decode, but still real data.
#
# HAND-VERIFIED INTERIM SET, not generated. The plan's Tier B replaces it with
# a generated "rotation_is_variant" field in unit_graphic_map.json, sourced
# from the .dat's own unit.class_ the way tools/gen_tree_unit_ids.py sources
# TREE_CLASS. Aqueduct (231) and Granary (1089) are deliberately absent: 10 and
# 0 corpus placements respectively is too thin to conclude either way.
_ROTATION_VARIANT_CONSTS: frozenset[int] = frozenset({
    72, 117, 119, 155, 370, 788, 1062, 2678,
})


def _rotation_is_variant(unit_const: int) -> bool:
    # Tier A (interim): see _ROTATION_VARIANT_CONSTS above. Swap this body for
    # `graphic_map()[unit_const].get("rotation_is_variant", False)` once Tier B
    # lands.
    return unit_const in _ROTATION_VARIANT_CONSTS


def variant_index(rotation: float, angle_count: int) -> int:
    """Which stored frame a rotation selects when the graphic's frames are
    shape variants rather than facings -- walls, confirmed by direct frame
    decode (see below).

    b_west_wall_stone_x1's five frames were decoded and inspected: 0 and 1 are
    wall runs along each screen diagonal, 2 is a tall tower, 3 a flatter run,
    4 a narrow column. A wall cannot be *rotated* into a tower, so the field
    selects a shape. Correlating rotation against wall connection topology
    across the example corpus confirmed integers 0..4 map 1:1 onto them.

    Real files use TWO conventions for the same graphic, and the corpus scan
    found a rare THIRD, so:

    - `rotation` within 1e-6 of an integer in [0, angle_count) is the variant
      index written directly -- use it as-is.
    - Otherwise treat it as that same index re-encoded as
      `index * 2*pi / angle_count` radians (the other convention real files
      ship) and solve for it with the ordinary angle formula.
    - That also absorbs the rare hand-rotated outlier (measured: one 5.969026
      among 1361 Palisade Wall placements, one each of 3.298672 and 4.084071
      among 4437 Stone Wall placements). There is no "correct" discrete frame
      for a freely-rotated wall piece, since the premise is that the frames are
      a few discrete shapes rather than a continuum; this just picks one
      deterministically, as angle_index() already does for off-grid values.

    The closeness test is against the RAW rotation, not against the angle
    formula's rounded output, and that distinction is load-bearing: at
    angle_count 5, index 2's radian encoding is 2.513274, which is CLOSER to 3
    than to 2 (0.4867 vs 0.5133), so "round the raw value to nearest int" would
    misfile it as 3. Testing raw closeness to an exact integer instead routes
    2.513274 to the angle branch, which resolves it to exactly 2, because
    0.4867 is nowhere near the 1e-6 window a literally-written index lands in.

    NEVER applies ANGLE_ZERO_OFFSET_DEG, by construction rather than because it
    happens to be skipped at angle_count 5. That offset corrects a physical
    camera-relative facing; a variant-index graphic has no facing to correct,
    so applying it would be wrong even for a future wall-like graphic whose
    angle_count did happen to be a multiple of 8.
    """
    if angle_count <= 1:
        return 0
    nearest = round(rotation)
    if abs(rotation - nearest) < 1e-6 and 0 <= nearest < angle_count:
        return int(nearest)
    steps = rotation / (2 * math.pi) * angle_count
    # floor(x + 0.5) rather than round(), for the same banker's-rounding reason
    # angle_index() spells out.
    return math.floor(steps + 0.5) % angle_count


def _graphics_dir() -> Path | None:
    root = asset_source.get_install_path()
    return None if root is None else root / GRAPHICS_SUBPATH


def _native_frame(file_name: str, frame_index: int):
    """(main, playercolor, hotspot_x, hotspot_y) at native resolution, or None.

    Swallows every failure into None on purpose -- see the module docstring.
    decode_frame() is the half that RAISES (SLDError, on a command stream that
    overruns its own block grid); load_sld() is the half that never does.
    """
    key = (file_name, frame_index)
    hit = _native_cache.get_or_none(key)
    if hit is not None:
        return hit

    directory = _graphics_dir()
    if directory is None:
        return None
    sld = load_sld(directory / f"{file_name}.sld")
    if sld is None:
        return None
    # The .dat's angle_count * frame_count overruns the real frame count on a
    # small minority of graphics, so trust the file, not the arithmetic.
    if not (0 <= frame_index < sld.frame_count):
        return None
    try:
        frame = sld.decode_frame(frame_index)
    except SLDError as exc:
        debug_log.log(f"sprite: {file_name} frame {frame_index} failed to decode: {exc}")
        return None
    if frame.main is None:
        return None
    # DAMAGE is deliberately not composited: it is a packed mask that BC1
    # happens to carry, not colour. SHADOW and OUTLINE are likewise skipped.
    value = _cropped_to_ink(frame.main, frame.playercolor, frame.hotspot_x, frame.hotspot_y)
    if value is None:
        return None
    _native_cache.put(key, value)
    return value


def _cropped_to_ink(main: np.ndarray, playercolor: np.ndarray | None, hx: int, hy: int):
    """(main, playercolor, hotspot_x, hotspot_y) trimmed to MAIN's opaque bbox.

    **A frame's canvas is mostly empty, and keeping the margin is expensive
    twice over.** Measured across 200 real graphics, the opaque bbox is a
    median 6% and a mean 10% of the canvas area -- a villager's ink is 15x39
    inside a 200x200 canvas. Uncropped, that margin is cached as RGBA bytes and
    then alpha-blended, pixel by pixel, on every composite that touches the
    sprite.

    Cropping moves the hotspot, so it is returned rebased rather than left for
    the caller to correct -- a sprite whose hotspot still refers to the
    uncropped canvas lands a whole margin's width off its tile.

    None if the frame has no opaque pixel at all: there is nothing to draw, and
    a zero-size array would only fail further downstream.
    """
    opaque = main[..., 3] > 0
    if not opaque.any():
        return None
    rows = np.flatnonzero(opaque.any(axis=1))
    cols = np.flatnonzero(opaque.any(axis=0))
    y0, y1 = int(rows[0]), int(rows[-1]) + 1
    x0, x1 = int(cols[0]), int(cols[-1]) + 1
    # np.ascontiguousarray so the cache holds the crop's own bytes rather than
    # a view keeping the whole decoded canvas alive.
    cropped_main = np.ascontiguousarray(main[y0:y1, x0:x1])
    cropped_pc = None if playercolor is None else np.ascontiguousarray(playercolor[y0:y1, x0:x1])
    return cropped_main, cropped_pc, hx - x0, hy - y0


def _tinted(main: np.ndarray, playercolor: np.ndarray | None, team: tuple[int, int, int]):
    """main * team, applied through playercolor's coverage. See the module
    docstring for why this is a multiply and not a palette lookup."""
    if playercolor is None or team == (255, 255, 255):
        return main
    rgb = main[..., :3].astype(np.float32)
    cov = np.where(playercolor[..., 3] > 0, playercolor[..., 0], 0).astype(np.float32) / 255.0
    cov = cov[..., None]
    t = np.array(team, dtype=np.float32) / 255.0
    out = main.copy()
    out[..., :3] = np.clip(rgb * (1 - cov) + rgb * t * cov, 0, 255).astype(np.uint8)
    return out


def _resize_rgba(rgba: np.ndarray, width: int, height: int) -> np.ndarray:
    """Nearest-neighbour box resample. Deliberately not Pillow: this module
    stays Qt-free and image-library-free like the rest of the render path, and
    a sprite shrunk to tile scale is being decimated, not enlarged."""
    src_h, src_w = rgba.shape[:2]
    ys = np.minimum((np.arange(height) * src_h) // height, src_h - 1)
    xs = np.minimum((np.arange(width) * src_w) // width, src_w - 1)
    return rgba[ys[:, None], xs[None, :]]


def sprite_scale(half_w: int) -> float:
    """Native sprite pixels -> canvas pixels, for a projection whose tile
    diamond is 2*half_w wide. One expression, so the mip ladder and any
    tile_px change follow it for free."""
    return 2 * half_w / NATIVE_TILE_W


def _draw_for_entry(
    unit_const: int, entry: dict, rotation: float, team_index: int, half_w: int
) -> SpriteDraw | None:
    """The tinted, scaled sprite `entry` (one graphic_map() record) resolves
    to, or None on any of the failure paths sprite_for()'s docstring lists.

    `unit_const` is a parameter, not read off `entry`, so a piece can pass its
    OWN resolving unit_id here (see sprite_pieces_for()) while `entry` still
    carries that piece's own file_name/angle_count/frame_count -- a piece's
    frame dispatch is a property of its own graphic, never of whichever unit
    happens to be standing on the map.

    `team_index` is TEAM_COLORS' own index (0 = GAIA, 1..8 = that ColorId's
    tint), not a player_id -- a scenario's stored color override can put any
    player on any tint, so the caller resolves player_id -> team_index
    itself (see scenario_io.LoadedScenario.team_indices) before calling
    here."""
    angle_count = max(1, int(entry["angle_count"]))
    frame_count = max(1, int(entry["frame_count"]))
    frame = (
        variant_index(rotation, angle_count)
        if _rotation_is_variant(unit_const)
        else angle_index(rotation, angle_count)
    )
    index = frame * frame_count

    scale = sprite_scale(half_w)
    team = TEAM_COLORS[team_index % len(TEAM_COLORS)]
    # Keyed on team_index, not player_id: two scenarios' player 1 can resolve
    # to different stored colors, and this cache is a process-global LRU that
    # would otherwise serve one scenario's tinted sprite to the other's.
    key = (entry["file_name"], index, team_index % len(TEAM_COLORS), half_w)
    hit = _scaled_cache.get_or_none(key)
    if hit is not None:
        return None if hit is _MISS else hit

    native = _native_frame(entry["file_name"], index)
    if native is None:
        _scaled_cache.put(key, _MISS)  # see _MISS -- re-deriving this is expensive
        return None
    main, playercolor, hx, hy = native

    width = max(1, round(main.shape[1] * scale))
    height = max(1, round(main.shape[0] * scale))
    draw = SpriteDraw(
        rgba=_resize_rgba(_tinted(main, playercolor, team), width, height),
        hotspot_x=round(hx * scale),
        hotspot_y=round(hy * scale),
    )
    _scaled_cache.put(key, draw)
    return draw


def sprite_for(
    unit_const: int, rotation: float, team_index: int, half_w: int
) -> SpriteDraw | None:
    """This unit's tinted, scaled sprite, or None to fall back to a mark.

    None is returned, never an exception, for every one of: a unit_const with
    no graphic; no install configured; the .sld missing on this install; the
    file unreadable (bad magic, zero bytes, or a layout variant that is neither
    14 nor 16); a frame index past the file's real end; and a frame whose
    decode raises.

    For a composite building (unit_graphic_map.json's optional "pieces" key),
    this draws only the entry's OWN graphic -- unchanged behavior for every
    existing caller. sprite_pieces_for() is the composite-aware sibling.
    """
    entry = graphic_map().get(unit_const)
    if entry is None:
        return None
    return _draw_for_entry(unit_const, entry, rotation, team_index, half_w)


def sprite_pieces_for(
    unit_const: int, rotation: float, team_index: int, half_w: int
) -> list[SpritePiece]:
    """The full ordered composite for unit_const: ready-to-paste pieces, each
    with its own (dx, dy) screen offset from the unit's own anchor. Empty on
    total failure (no entry, or the parent piece fails to resolve) so the
    caller falls back to today's coloured mark, unchanged. A unit_const with
    no "pieces" key resolves to a single piece at (0, 0) -- callers do not
    need two code paths for a composite vs. a plain unit.

    A non-parent piece that fails to resolve is skipped rather than failing
    the whole composite -- strictly better than today, never worse. Each
    piece resolves through its OWN resolving unit_id (unit_graphic_map.json's
    per-piece "unit_id" -- this const itself for the parent's own piece, an
    annex's unit_id otherwise), never unit_const for every piece: a piece's
    frame dispatch is a property of its own graphic (see _draw_for_entry),
    and pieces can carry a different angle_count/rotation-dispatch than their
    parent even though every currently-composited piece is angle-index-based
    like its parent today.
    """
    entry = graphic_map().get(unit_const)
    if entry is None:
        return []
    pieces_data = entry.get("pieces")
    if not pieces_data:
        draw = _draw_for_entry(unit_const, entry, rotation, team_index, half_w)
        return [] if draw is None else [SpritePiece(draw=draw, dx=0, dy=0)]

    scale = sprite_scale(half_w)
    result: list[SpritePiece] = []
    for piece in pieces_data:
        draw = _draw_for_entry(piece["unit_id"], piece, rotation, team_index, half_w)
        if draw is None:
            # The parent's own piece (unit_id == unit_const) is identified by
            # identity, not list position -- depth order can (and for a town
            # centre's back piece, does) place it anywhere but index 0.
            if piece["unit_id"] == unit_const:
                return []
            continue
        result.append(SpritePiece(
            draw=draw,
            dx=round(piece["dx"] * scale),
            dy=round(piece["dy"] * scale),
        ))
    return result


def anchor_tile_coords(
    tile_x0: int, tile_y0: int, span_x: int, span_y: int
) -> tuple[float, float]:
    """The continuous tile coordinate a sprite's hotspot sits on: the
    FOOTPRINT'S CENTRE, not the anchor tile's diamond centre (those differ by
    half a tile on an even span) and not the sprite's top-left corner, which is
    what a naive blit does and what offsets every sprite from its tile.

    Verified against the game's own art: a 3x3 Barracks' stone base lands on
    exactly its own footprint diamond under this rule, with only the palisade
    overhanging -- which is what it does in game."""
    return tile_x0 + span_x / 2, tile_y0 + span_y / 2


def sprite_anchor_tile(
    tile_x0: int, tile_x1: int, tile_y0: int, tile_y1: int
) -> tuple[int, int]:
    """Which footprint tile's moment in the depth walk paints the sprite.

    A sprite is ONE image over the whole footprint, so it must paint once --
    unlike the diamond path, where _units_by_tile buckets a building into every
    footprint tile and each diamond lands at its own tile's depth position.

    The tile chosen is the one that comes LAST in depth_order: maximal
    d = y - x, tie-broken on ascending x, the same key composite_rect_iso's own
    np.lexsort((xs, ys - xs)) uses. Reusing that key rather than an ad-hoc
    max(x + y) matters because a divergence here is a paint-order mismatch that
    tests/test_unit_pick.py's ID-plane oracle cannot catch -- picking still goes
    through the diamond path and is unaffected by sprites.

    Painting last within the footprint means every footprint tile's terrain is
    already down, while terrain nearer than the building still paints over the
    sprite, exactly as it does for diamonds today.
    """
    best = None
    for ty in range(tile_y0, tile_y1):
        for tx in range(tile_x0, tile_x1):
            key = (ty - tx, tx)
            if best is None or key > best[0]:
                best = (key, (tx, ty))
    return best[1]
