"""Resolves a unit to its real in-game sprite: unit_const -> .sld frame -> a
tinted, scaled RGBA array the Stepped compositor can paste.

Leaf module. numpy and stdlib only -- no Qt, no genieutils, and nothing here
reaches into descape/render.py.

**No game assets are shipped.** Pixels are read from the user's own configured
AoE2:DE install at runtime, the same posture asset_source.py takes for terrain
textures. descape/unit_graphic_map.json (committed, generated by
tools/gen_unit_graphic_map.py) is a factual data table extracted from the
game's unit and graphic tables, not asset content.

Everything below falls back to None rather than raising. A caller that gets
None draws today's coloured mark, so an absent install, an absent file, an
unreadable file and an undecodable frame are all exactly as safe as "no install
configured" already is.

## How a unit becomes a frame

A graphic's frames are stored **angle-major**: `frames[angle * frame_count]` is
that angle's first (standing) pose, which is the only one a scenario editor
needs -- there is no animation loop here. `angle_count` is the number of angles
actually stored; `mirroring_mode` does NOT halve it, despite the usual AoE2
convention (measured over 400 graphics: total_frames - angle_count*frame_count
is 0 or 1, never half, and a graphic's stored frames are pixel-distinct rather
than mirrored duplicates). Animated graphics carry one extra frame at the END,
so no index offset is needed.

## How player colour is applied

The MAIN layer renders the player-coloured region in near-grey, and the
PLAYERCOLOR layer is a per-pixel COVERAGE mask (its interior sits at 255, its
boundary ramps -- it is antialiasing, not a shade index). The tint is a plain
multiply by one RGB per player:

    out = lerp(main, main * team_rgb, coverage)

TEAM_COLORS below are the game's own, read from its
resources/_common/palettes/spritecolors.json. The 256-entry playercolor_*.pal
files are the legacy SLP path and must NOT be used here: their entries 128..255
are all black, while MAIN's luminance under the mask reaches 247, so indexing
them by luminance paints most sprites black.
"""

from __future__ import annotations

import json
import math
from collections import OrderedDict
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import numpy as np

from descape import asset_source, debug_log
from descape.sld_decoder import SLDError, load_sld

GRAPHIC_MAP_PATH = Path(__file__).resolve().parent / "unit_graphic_map.json"
GRAPHICS_SUBPATH = "resources/_common/drs/graphics"

# DE's own iso tile diamond width for x1 assets. Measured against the spans the
# game's unit table reports, not read off a wiki: a building sprite's ink
# extends symmetrically about its hotspot by span * 96 / 2 in x and reaches
# span * 96 / 4 below it in y (House 2x2 -84..+79 vs +-96; Barracks 3x3
# -148..+140 vs +-144; Wonder 5x5 -249..+248 vs +-240).
NATIVE_TILE_W = 96

# How far the farthest sprite's pixels reach past its own hotspot, per side, in
# the same native px NATIVE_TILE_W is in -- so a canvas-pixel padding is
# reach * sprite_scale(half_w). descape/render.py's _sprite_reach_px is the only
# consumer: it turns these into the per-side widening an edit's dirty bbox needs
# so a sprite standing on a dirty tile cannot escape it and leave a stale
# fragment behind.
#
# Measured by tools/scan_sprite_reach.py over every .sld descape/
# unit_graphic_map.json references, from each frame's MAIN-layer header box
# (which bounds the ink bbox _cropped_to_ink produces). The worst file is named
# per direction so a re-scan after a game patch either reproduces the number or
# says which graphic grew. UP dominates by a wide margin -- wonders and
# cathedrals out-reach every horizontal case by 50%.
#
# DOWN grew from 200 to 316 with the class-39 gate composite (2026-09-02):
# a bare directional city gate's own
# flag POSITION is its corner-pillar annex's misplacement, but the flag
# GRAPHIC's own delta offset (dy=-240, roughly double the west-stone gate
# family's -120) is a property of that piece alone -- composited pieces can
# out-reach every plain single-graphic unit measured before them, which is
# exactly why scan_sprite_reach.py scans pieces at their own offset rather
# than the parent's.
MAX_SPRITE_REACH_LEFT = 404   # b_scen_cathedral_rubble_x1
MAX_SPRITE_REACH_RIGHT = 424  # b_scen_cathedral_rubble_x1
MAX_SPRITE_REACH_UP = 650     # b_west_wonder_britons_x1
MAX_SPRITE_REACH_DOWN = 316   # b_scen_gate_city_flag_x1 (piece, dx=0 dy=-312)

# How far the stored angle set is rotated from the scenario's own `rotation`
# field, in degrees, and which way the index walks as rotation increases.
#
# **The offset is ANGULAR, not an index offset, and that distinction is the
# whole reason this constant is in degrees.** Index 0 is a fixed compass
# direction for every graphic regardless of how many angles it stores, so a
# correction of "45 degrees" is 1 step for an angle_count of 8 but 2 for 16 and
# 4 for 32. angle_count is nowhere near uniform -- measured over the 2,439
# graphics unit_graphic_map.json references, 16 dominates at 1,163 and 8 is
# rare at 76, with everything from 2 to 72 present. An index-space constant
# (which this was until 2026-08-24) therefore cannot express a fixed angular
# correction at all: it would rotate most units by 22.5 degrees while rotating
# a handful by 45.
#
# The magnitude comes from a live-window observation: units rendered 45 degrees
# to the RIGHT of where the real editor puts them, uniformly. Uniformly is the
# load-bearing word -- a wrong ANGLE_DIRECTION would MIRROR the facing about an
# axis, so the error would vary with rotation instead of being constant. That
# it is constant is what says the direction is already right and only the zero
# point was off.
#
# **The sign is -45, confirmed against the running game, and it is worth
# knowing WHY it is not +45.** Correcting a "units face 45 degrees too far
# right" error means adding 45 degrees if the game's `rotation` grows
# counter-clockwise and subtracting it if clockwise. Nothing in the .sld, the
# .dat or openage states which, so +45 was tried first on the reasoning that a
# radians field usually follows the maths convention. That put units 90 degrees
# out -- the signature of a sign error, being exactly twice the offset -- so
# **AoE2's rotation field grows CLOCKWISE on screen.** Recorded here because it
# cost a round trip to a human with the game open, and nothing else in this
# codebase pins it.
ANGLE_ZERO_OFFSET_DEG = -45.0
ANGLE_DIRECTION = 1

# resources/_common/palettes/spritecolors.json's TeamColors block, as RGB.
# Index is the scenario's own player id: 0 is GAIA, 1..8 the real players.
# GAIA's (255, 255, 255) multiplies to identity, so a GAIA unit needs no
# special case anywhere.
TEAM_COLORS = (
    (255, 255, 255),  # GAIA
    (0, 0, 255),
    (255, 0, 0),
    (0, 169, 27),
    (214, 214, 27),
    (123, 239, 240),
    (138, 19, 247),
    (102, 102, 102),
    (255, 146, 5),
)

# Sized by tools/bench_unit_sprites.py (P3-g4), not guessed. Both matter
# because sld_decoder holds no cache of its own and a delta chain can be 313
# links deep, so one wanted frame can pay for hundreds of predecessor decodes.
#
# **The failure mode these avoid is a cache that silently does nothing.** At
# the first-pass 256, the worst real file (old-allies-final-v2, 652 distinct
# (file, frame) pairs before the per-player and per-mip-level multiplier) ran
# a WARM layer rebuild in 4562ms against a 4768ms cold one -- every entry was
# evicted before it could be reused, so the cache cost memory and bought
# nothing. It is not enough for a capacity to be "big"; it has to exceed a
# real file's distinct-key count, or it is worse than no cache at all.
#
# Entry counts rather than a byte budget, because cropping to the ink bbox
# made entries small and predictable: measured across the three biggest
# example files, a scaled entry averages ~19KB and a native one ~200KB. So
# these caps are roughly 40MB scaled and 50MB native at worst, and typically a
# small fraction of that.
NATIVE_CACHE_SIZE = 256
SCALED_CACHE_SIZE = 2048

# Flat's icon cache (P3-g7), a BYTE budget rather than an entry count -- see
# _ByteLRU for why an entry count cannot work here.
#
# **Measured, and the first try was too small in exactly the way P3-g4 warns
# about.** The distinct-key count is consts x frames x teams x footprint
# sizes, and the footprint-size axis is the new one: one entry per mip level
# per span, and an entry is footprint-sized, so a level's whole working set
# quadruples with each step up the ladder. On the worst real example file
# (old-allies-final-v2, 240x240, 13,099 units) the four enumerated levels want
# 1.3 / 5.2 / 20.9 / 83.7MB for 899 entries each, 111.2MB in total. At a
# first-pass 64MB the tile_px=128 level alone did not fit, and its WARM
# rebuild ran in 4181ms against a 4023ms cold one -- every entry evicted
# before reuse, the cache costing memory and buying nothing, which is the same
# failure NATIVE_CACHE_SIZE/SCALED_CACHE_SIZE's own comment records. 128MB
# clears that file's whole ladder; in practice only resident levels are ever
# built (see FlatChunkCache._level_icons' laziness), so one or two of those
# four is the normal steady state.
ICON_CACHE_BYTES = 128 * 1024 * 1024


@dataclass(frozen=True)
class SpriteDraw:
    """One unit's sprite, ready to paste.

    rgba is (h, w, 4) uint8 already tinted for its owner and already scaled for
    the caller's tile_px. hotspot_x/y are in that same scaled pixel space, and
    are the pixel that sits on the ground anchor -- see anchor_screen_pos().
    """

    rgba: np.ndarray
    hotspot_x: int
    hotspot_y: int


@dataclass(frozen=True)
class SpritePiece:
    """One piece of a composite building's sprite (a town centre's back/main/
    center/front, a pasture's corner posts), ready to paste at an offset from
    the unit's own anchor. dx/dy are in the same scaled canvas-pixel space as
    SpriteDraw's hotspot -- see sprite_pieces_for()."""

    draw: SpriteDraw
    dx: int
    dy: int


class _LRU(OrderedDict):
    """Smallest thing that is actually an LRU. functools.lru_cache can't be
    used for the scaled cache: its capacity has to stay adjustable from
    P3-g4's bench without redecorating a module-level function."""

    def __init__(self, capacity: int):
        super().__init__()
        self.capacity = capacity

    def get_or_none(self, key):
        if key in self:
            self.move_to_end(key)
            return self[key]
        return None

    def put(self, key, value):
        self[key] = value
        self.move_to_end(key)
        while len(self) > self.capacity:
            self.popitem(last=False)


class _ByteLRU(OrderedDict):
    """An LRU capped by the total BYTES its values hold, not by entry count.

    _LRU's entry cap works for _scaled_cache because cropping to the ink bbox
    made entries small and uniform (~19KB measured). An icon entry is
    FOOTPRINT-sized instead -- a 1x1 unit at tile_px=16 is ~1KB and a 4x4 Town
    Centre at tile_px=128 is ~1MB -- so any single entry count is either
    wasteful at one end of that spread or thrashing at the other.
    """

    def __init__(self, capacity_bytes: int):
        super().__init__()
        self.capacity_bytes = capacity_bytes
        self._bytes = 0

    @staticmethod
    def _size(value) -> int:
        # A _MISS costs nothing to hold and (see below) a great deal to
        # re-derive, so it is charged a nominal byte rather than 0 -- at 0 an
        # unbounded number of them could accumulate.
        return value.rgba.nbytes if isinstance(value, SpriteDraw) else 1

    def get_or_none(self, key):
        if key in self:
            self.move_to_end(key)
            return self[key]
        return None

    def put(self, key, value):
        if key in self:
            self._bytes -= self._size(self[key])
        self[key] = value
        self._bytes += self._size(value)
        self.move_to_end(key)
        # len() > 1 so a single entry larger than the whole budget is still
        # served rather than evicted the instant it is stored.
        while self._bytes > self.capacity_bytes and len(self) > 1:
            _key, evicted = self.popitem(last=False)
            self._bytes -= self._size(evicted)

    def clear(self) -> None:
        super().clear()
        self._bytes = 0


_native_cache = _LRU(NATIVE_CACHE_SIZE)
_scaled_cache = _LRU(SCALED_CACHE_SIZE)
_icon_cache = _ByteLRU(ICON_CACHE_BYTES)

# Cached in place of a sprite when a key resolves to nothing.
#
# **It lives in _native_cache**, keyed (file_name, frame_index), which is
# scale-independent -- so every scale, every mip level and every consumer
# (Stepped, Sloped, Flat's icons) share one negative answer. P3-g7 moved it
# down here from _scaled_cache, whose key carries a half_w: an icon's key
# carries a footprint size instead, so it could not have inherited the
# scaled-level misses and would have re-walked every unresolvable file once
# per footprint size per mip level. _scaled_cache still puts its own _MISS
# too; that is now redundant rather than wrong, and removing it is a separate
# cleanup.
#
# **Caching the negative result is not an optimization, it is the difference
# between a working cache and a broken one.** A unit that resolves nowhere --
# no file on this install, a frame index past the file's end -- costs a full
# SLDFile walk to discover that, every single time.
# Measured on the 32,272-unit corpus outlier before this existed: a WARM layer
# rebuild spent 1.59s of its 1.74s inside SLDFile.__init__, re-walking files
# 641 times to re-derive answers it already had. Only ~1% of that file's units
# are unresolvable; they were most of its cost.
_MISS = object()


def clear_caches() -> None:
    """Drops every LRU. For tests, and for a settings change that repoints the
    install path -- a cached array outlives the file it came from otherwise,
    and every one of these remembers MISSES too, so a first-time install
    configuration would keep serving "no sprite" without this."""
    _native_cache.clear()
    _scaled_cache.clear()
    _icon_cache.clear()
    sld_frame_count.cache_clear()


@lru_cache(maxsize=1)
def graphic_map() -> dict[int, dict]:
    """unit_const -> {graphic_id, file_name, angle_count, mirroring_mode,
    frame_count}, from the committed table."""
    data = json.loads(GRAPHIC_MAP_PATH.read_text())["graphics"]
    return {int(k): v for k, v in data.items()}


def angle_index(rotation: float, angle_count: int) -> int:
    """Which stored angle a rotation (radians) selects.

    Real rotations are NOT quantized -- across the example corpus 20,122
    non-GAIA units carry 34 distinct values, mixing exact 16-grid points with
    hand-typed round numbers, 40% of them 0.0, and ~4% outside [0, 2*pi)
    entirely (7.0 appears 574 times). So this rounds and wraps rather than
    looking anything up.

    GAIA is the caller's problem, not this function's: a GAIA object's
    `rotation` is a doodad graphic-variant index, not an angle (see AGENTS.md's
    hard rule), so it must never be passed here.
    """
    if angle_count <= 1:
        return 0
    steps = rotation / (2 * math.pi) * angle_count
    # ANGLE_ZERO_OFFSET_DEG is converted into THIS graphic's own step size --
    # see its comment for why a fixed index offset cannot do this job. Kept
    # outside the ANGLE_DIRECTION product deliberately: direction is how the
    # index walks as rotation grows, the offset is a fixed rotation of the
    # whole set, and multiplying the two would silently flip the correction if
    # the direction were ever changed.
    # The offset applies ONLY when it lands on a whole stored step -- i.e. when
    # angle_count is a multiple of 8, since the offset is 45 degrees. That is
    # what the offset MEANS, not a special case for any one graphic: a
    # zero-point correction rotates which stored angle a rotation selects, so
    # if it does not map stored angles onto stored angles then the graphic's
    # angle set is not a 45-degree-compatible sampling of the circle, and there
    # is no sense in which it is "45 degrees out". It fires for every
    # angle_count that is not a multiple of 8, and 3, 6, 7, 9 and more are all
    # in real use.
    #
    # Walls are the case that motivated writing it down. They store 5 angles,
    # where 45 degrees is 0.625 of a step, so applying the offset re-quantized
    # every facing to a neighbour and moved walls a full 72-degree frame
    # (reported from a live window 2026-08-24, the same session the offset was
    # added for units). Walls no longer reach this function at all -- their
    # frames are shape variants rather than facings, so rotation_is_variant()
    # diverts them to variant_index() -- but the skip above is general and
    # stays.
    offset_steps = ANGLE_ZERO_OFFSET_DEG / 360.0 * angle_count
    if offset_steps != int(offset_steps):
        offset_steps = 0.0
    # Rounds the SUM, not each term: the offset is exact only when angle_count
    # is a multiple of 8 (16 -> 2.0, 8 -> 1.0), and 25 -> 3.125 is a real case.
    # Rounding once is rounding the final angle, which is the quantity that has
    # to land on a stored frame.
    #
    # floor(x + 0.5), not round(): round() is banker's rounding, which breaks
    # exact .5 ties toward EVEN and so breaks them inconsistently. That only
    # became reachable once the offset could be fractional -- at angle_count 4
    # a 45-degree offset is exactly half a step, and banker's rounding then
    # sent rotations 0 and pi/2 to the same stored angle while pi and 3pi/2
    # went to different ones. Half-up is arbitrary too, but uniformly so, which
    # is what keeps distinct facings distinct.
    return math.floor(ANGLE_DIRECTION * steps + offset_steps + 0.5) % angle_count


# Confirmed 2026-08-25: these
# unit_consts' stored frames are shape variants (wall run/tower/column/etc.),
# not facings, so their `rotation` field must go through variant_index()
# rather than angle_index(). 117 by direct frame decode. 72/119/788 share one
# file_name (b_dark_wall_palisade_flag_x1) among THEMSELVES, not with 117, so
# they must share its behaviour regardless of class. 155
# (b_west_wall_fortified_x1) shows the same mixed integer/exact-k*2pi/5-radian
# rotation pattern as 117 and 72, i.e. the same real Wall family.
#
# 370/1062/2678 (City Wall, Fence, scenario Fortified Wall) rest only on that
# plan's rotation-value corpus profiling -- integer-only, never the wide
# hand-typed spread angle_index()'s own docstring measures for genuine facing
# graphics. Weaker evidence than a direct decode, but still real data.
#
# No longer rotation_is_variant()'s data source (2026-09-06 Tier B plan --
# that reads unit_graphic_map.json's generated field now, sourced from the
# .dat's own unit.type != 70, not unit.class_ as originally proposed: class_
# == 27 also catches 28 non-wall consts like "Sheep annex1" and "Empty
# building"). This set's remaining job is WALL_CONNECTOR_CONSTS and
# rotation_variant_eligible() below, where "exactly today's 8 walls" is
# deliberately still hand-kept -- widening it further would let a water lily
# or an Aqueduct get its stored index rederived from a wall-calibrated
# neighbour mask.
_ROTATION_VARIANT_CONSTS: frozenset[int] = frozenset({
    72, 117, 119, 155, 370, 788, 1062, 2678,
})


# Cliffs (2026-09-05 cliffs plan, Track A2). Every `class_ == 34` const in the
# .dat: ten full families of nine pieces, plus the six-const CLF01..CLF08
# partial family at 1339-1346 that shares the Desert graphic (the plan's own
# const ranges missed that one -- it was found by re-measuring the class from
# the .dat rather than transcribing the ranges).
#
# A family's ~24 stored frames are SHAPES (runs, corners, ends) selected by
# `rotation`, the same convention as the wall set above, and the corpus
# evidence is stronger than for any wall const: 18,232 of 18,232 cliff records
# store an exact integer in [0, 24] and `rotation == initial_animation_frame`
# in every one. Zero radian encodings.
#
# **Kept separate from _ROTATION_VARIANT_CONSTS on purpose.** Both used to
# feed rotation_is_variant() directly; since the 2026-09-06 Tier B plan that
# predicate reads unit_graphic_map.json's generated field instead (which
# independently agrees this set is variant-indexed), but this frozenset stays
# because cliff_consts() still backs cliff_catalog.py/cliff_chain.py's
# family/piece grouping, and folding it into _ROTATION_VARIANT_CONSTS would
# make every cliff count as a wall neighbour and reshape real walls through
# wall_variant_rotation_overrides(). Cliffs connect to cliffs, not to walls.
#
# Pinned against the .dat by tests/test_unit_footprints.py, which asserts this
# equals terrain_palette.OBJECT_TILE_SPANS' key set -- generated from the same
# class_ == 34 gate -- rather than trusting the ranges written here.
_CLIFF_VARIANT_CONSTS: frozenset[int] = frozenset(
    list(range(264, 273))
    + [1339, 1340, 1341, 1342, 1344, 1346]
    + list(range(1849, 1867))
    + list(range(2069, 2078))
    + list(range(2178, 2187))
    + list(range(2190, 2226))
    + list(range(2651, 2660))
)


def rotation_is_variant(unit_const: int) -> bool:
    """Whether unit_const's `rotation` field selects a shape variant
    (variant_index()) rather than a facing (angle_index()) -- Tier B
    (2026-09-06 plan): reads unit_graphic_map.json's generated field, sourced
    from the .dat's own unit.type != 70 (non-creatable) with the trebuchet
    consts forced false, in preference to the two hand-kept frozensets above
    (which stay, for their own other callers -- see their comments)."""
    return bool(graphic_map().get(unit_const, {}).get("rotation_is_variant", False))


def cliff_consts() -> frozenset[int]:
    """The public read of `_CLIFF_VARIANT_CONSTS`, for cliff_catalog.py's
    family/piece grouping -- kept a function, not a re-exported name, so
    every caller goes through one place if Tier B ever replaces the set."""
    return _CLIFF_VARIANT_CONSTS


# HAND-VERIFIED against examples/ (2026-09-02 counterexamples plan), same
# provenance discipline as _ROTATION_VARIANT_CONSTS above: 64/88/95/659/667/
# 793/797 are the gate consts that plan's corpus scan found placed alongside
# the confirmed wall family. Gates are load-bearing for connectivity, not
# incidental -- walls-only connectivity measured 93.5% mask->index agreement
# on the integer corpus, walls+gates measured 98.7%. class_ == 39 is WIDER
# than "gates" (it also catches corner-pillar consts like 81), and including
# the wider set was measured and rejected (96.9%), so this stays a hand-kept
# list rather than "every class-39 const" until a generated replacement
# derives and validates this from the .dat's own unit.class_ field instead.
WALL_CONNECTOR_CONSTS: frozenset[int] = _ROTATION_VARIANT_CONSTS | frozenset({
    64, 88, 95, 659, 667, 793, 797,
})


WEST, EAST, NORTH, SOUTH = 1, 2, 4, 8


def wall_variant_from_neighbours(mask: int) -> int | None:
    """Derives a wall/gate's shape from which orthogonal neighbours are also
    connectors, calibrated against the integer-encoded corpus (2026-09-02
    counterexamples plan): mask bits are WEST=1, EAST=2, NORTH=4, SOUTH=8.

    - exactly {WEST, EAST}  -> 0 (run along x)   -- 98.9% agreement, n=1835
    - exactly {NORTH, SOUTH} -> 1 (run along y)  -- 99.1% agreement, n=1882
    - any other non-zero mask -> 2 (tower/corner/junction) -- 96-100%, n=1323
    - no neighbours (mask 0) -> None: an isolated piece's shape is
      author-chosen, not derivable, and must fall through to the caller's
      existing (stored-value) resolution rather than being guessed.
    """
    if mask == 0:
        return None
    if mask == WEST | EAST:
        return 0
    if mask == NORTH | SOUTH:
        return 1
    return 2


def rotation_variant_eligible(unit_const: int) -> bool:
    """Preconditions 1-2 of the connectivity override (2026-09-03 execute
    plan): the const is a variant-index graphic, and its angle_count is 5 --
    the 3-case mask table above does not transfer to another frame count.

    Gates on `_ROTATION_VARIANT_CONSTS` rather than `rotation_is_variant()`
    (2026-09-06 Tier B plan): that predicate widened from 8 consts to every
    unit.type != 70 graphic, which would also make Aqueduct, Granary, a water
    lily and a dozen other non-wall consts eligible for the wall-connectivity
    override -- a water lily between two walls would have its stored index
    rederived from a wall-calibrated neighbour mask, which is wrong. The
    wall-family basis stays deliberately hand-kept here: `class_ == 39` was
    measured and rejected for WALL_CONNECTOR_CONSTS' own gate set, and a
    generated `wall_family` flag is a future replacement, not this pass's job.
    `WALL_CONNECTOR_CONSTS` (the *neighbour tile* set) is unchanged either way.

    Preconditions 3 (not a literal integer index) and 4 (non-zero neighbour
    mask) are NOT checked here. Measured (tools/scan_wall_rotation.py): of the
    literal-0.0-rotation walls in the 7 corpus files that also carry
    radian-encoded wall rotations, 45.6% (241/529) sit on a non-zero mask
    whose derived index isn't 0 -- far more than "a handful", so condition 3
    cannot be a per-unit literal-value check. Inside a file that uses the
    radian convention at all, a literal-looking 0.0 carries no more shape
    information than any other radian value does (both stored conventions
    agree only at index 0), so the literal-vs-radian classification has to be
    made per SCENARIO FILE, not per unit -- and that requires seeing every
    wall's rotation at once, which this leaf module's per-unit signature
    can't do. render.wall_variant_rotation_overrides() does that
    classification and folds precondition 3 in; this predicate is preconditions
    1-2 only.

    Deliberately looks angle_count up via graphic_map() itself rather than
    taking it as a parameter, so render.py never has to reach into this
    module's data table directly."""
    if unit_const not in _ROTATION_VARIANT_CONSTS:
        return False
    entry = graphic_map().get(unit_const)
    return entry is not None and int(entry["angle_count"]) == 5


def is_literal_variant_index(rotation: float, angle_count: int) -> bool:
    """True when `rotation` is already a literal stored index rather than a
    radian encoding of one -- the same closeness test variant_index() applies,
    exposed standalone so render.py's per-file radian/integer classification
    doesn't duplicate the 1e-6 window."""
    nearest = round(rotation)
    return abs(rotation - nearest) < 1e-6 and 0 <= nearest < angle_count


def variant_index(rotation: float, angle_count: int, variant_count: int | None = None) -> int:
    """Which stored frame a rotation selects when the graphic's frames are
    shape variants rather than facings -- walls, confirmed by direct frame
    decode (see below).

    b_west_wall_stone_x1's five frames were decoded and inspected: 0 and 1 are
    wall runs along each screen diagonal, 2 is a tall tower, 3 a flatter run,
    4 a narrow column. A wall cannot be *rotated* into a tower, so the field
    selects a shape. Correlating rotation against wall connection topology
    across the example corpus confirmed integers 0..4 map 1:1 onto them.

    Real files use TWO conventions for the same graphic, and the corpus scan
    found a rare THIRD, so:

    - `rotation` within 1e-6 of an integer in [0, angle_count) is the variant
      index written directly -- use it as-is.
    - Otherwise treat it as that same index re-encoded as
      `index * 2*pi / angle_count` radians (the other convention real files
      ship) and solve for it with the ordinary angle formula.
    - That also absorbs the rare hand-rotated outlier (measured: one 5.969026
      among 1361 Palisade Wall placements, one each of 3.298672 and 4.084071
      among 4437 Stone Wall placements). There is no "correct" discrete frame
      for a freely-rotated wall piece, since the premise is that the frames are
      a few discrete shapes rather than a continuum; this just picks one
      deterministically, as angle_index() already does for off-grid values.

    The closeness test is against the RAW rotation, not against the angle
    formula's rounded output, and that distinction is load-bearing: at
    angle_count 5, index 2's radian encoding is 2.513274, which is CLOSER to 3
    than to 2 (0.4867 vs 0.5133), so "round the raw value to nearest int" would
    misfile it as 3. Testing raw closeness to an exact integer instead routes
    2.513274 to the angle branch, which resolves it to exactly 2, because
    0.4867 is nowhere near the 1e-6 window a literally-written index lands in.

    NEVER applies ANGLE_ZERO_OFFSET_DEG, by construction rather than because it
    happens to be skipped at angle_count 5. That offset corrects a physical
    camera-relative facing; a variant-index graphic has no facing to correct,
    so applying it would be wrong even for a future wall-like graphic whose
    angle_count did happen to be a multiple of 8.

    **`variant_count` is how many frames the file really holds; `angle_count`
    stays the radian encoding's own divisor.** They are the same number for
    walls but not for cliffs, and conflating them is a silent wrong answer
    rather than an error: the Short Cliff families declare angle_count 23 over
    a 24-frame file, so a literal stored 23 failed `nearest < angle_count`,
    fell through to the radian branch, and returned a plausible-looking wrong
    frame. The Marble family fails the other way (25 declared, 23 real), where
    the tighter bound keeps a literal 23/24 from resolving to a frame
    _native_frame() would then reject outright. Defaults to angle_count, which
    is the pre-existing behaviour for every caller that doesn't know better.

    **An exact integer at or past `variant_count` wraps, rather than falling
    through to the radian branch** (Tier B plan, 2026-09-06): 36.0 is not
    `k*2*pi/36` for any k, so treating an out-of-range literal as a radian
    encoding is definitionally wrong for it, not just imprecise. Measured
    against the corpus: mangrove (36..47 on a 36-frame file), forage bush
    (4.0/5.0 on 4 frames), skeleton (15.0 on 15) and mole (7.0 on 3) all store
    an exact integer past their own frame count and all drew frame 0 before
    this wrap existed.
    """
    if angle_count <= 1:
        return 0
    if variant_count is None:
        variant_count = angle_count
    nearest = round(rotation)
    if abs(rotation - nearest) < 1e-6:
        if 0 <= nearest < variant_count:
            return int(nearest)
        return int(nearest) % variant_count
    steps = rotation / (2 * math.pi) * angle_count
    # floor(x + 0.5) rather than round(), for the same banker's-rounding reason
    # angle_index() spells out.
    return math.floor(steps + 0.5) % angle_count


def _graphics_dir() -> Path | None:
    root = asset_source.get_install_path()
    return None if root is None else root / GRAPHICS_SUBPATH


@lru_cache(maxsize=512)
def sld_frame_count(file_name: str) -> int | None:
    """How many frames the .sld file actually holds, or None when it can't be
    read (no install configured, or the file is missing on this install).

    The .dat's `angle_count` is NOT this number and disagrees in BOTH
    directions -- measured on the cliff families: Marble declares 25 angles
    over a 23-frame file, while the Short families declare 23 over a 24-frame
    one. _native_frame() has always trusted the file over the arithmetic; this
    exposes the same count to the *dispatch* so variant_index() can range-check
    against it instead of against angle_count.

    Cheap enough to be a plain lru_cache: load_sld() parses the header and
    frame table, never a frame's pixels. Cleared by clear_caches() with the
    rest, since an install-path change invalidates it."""
    directory = _graphics_dir()
    if directory is None:
        return None
    sld = load_sld(directory / f"{file_name}.sld")
    return None if sld is None else int(sld.frame_count)


def _native_frame(file_name: str, frame_index: int):
    """(main, playercolor, hotspot_x, hotspot_y) at native resolution, or None.

    Swallows every failure into None on purpose -- see the module docstring.
    decode_frame() is the half that RAISES (SLDError, on a command stream that
    overruns its own block grid); load_sld() is the half that never does.
    """
    key = (file_name, frame_index)
    hit = _native_cache.get_or_none(key)
    if hit is not None:
        return None if hit is _MISS else hit

    directory = _graphics_dir()
    if directory is None:
        # The ONLY failure below that isn't negative-cached, and deliberately:
        # it is global install-path state, not a property of this
        # (file_name, frame_index). Costs nothing to re-derive either --
        # get_install_path() is itself lru_cached.
        return None
    sld = load_sld(directory / f"{file_name}.sld")
    if sld is None:
        _native_cache.put(key, _MISS)
        return None
    # The .dat's angle_count * frame_count overruns the real frame count on a
    # small minority of graphics, so trust the file, not the arithmetic.
    if not (0 <= frame_index < sld.frame_count):
        _native_cache.put(key, _MISS)
        return None
    try:
        frame = sld.decode_frame(frame_index)
    except SLDError as exc:
        debug_log.log(f"sprite: {file_name} frame {frame_index} failed to decode: {exc}")
        _native_cache.put(key, _MISS)
        return None
    if frame.main is None:
        _native_cache.put(key, _MISS)
        return None
    # DAMAGE is deliberately not composited: it is a packed mask that BC1
    # happens to carry, not colour. SHADOW and OUTLINE are likewise skipped.
    value = _cropped_to_ink(frame.main, frame.playercolor, frame.hotspot_x, frame.hotspot_y)
    if value is None:
        _native_cache.put(key, _MISS)
        return None
    _native_cache.put(key, value)
    return value


def _cropped_to_ink(main: np.ndarray, playercolor: np.ndarray | None, hx: int, hy: int):
    """(main, playercolor, hotspot_x, hotspot_y) trimmed to MAIN's opaque bbox.

    **A frame's canvas is mostly empty, and keeping the margin is expensive
    twice over.** Measured across 200 real graphics, the opaque bbox is a
    median 6% and a mean 10% of the canvas area -- a villager's ink is 15x39
    inside a 200x200 canvas. Uncropped, that margin is cached as RGBA bytes and
    then alpha-blended, pixel by pixel, on every composite that touches the
    sprite.

    Cropping moves the hotspot, so it is returned rebased rather than left for
    the caller to correct -- a sprite whose hotspot still refers to the
    uncropped canvas lands a whole margin's width off its tile.

    None if the frame has no opaque pixel at all: there is nothing to draw, and
    a zero-size array would only fail further downstream.
    """
    opaque = main[..., 3] > 0
    if not opaque.any():
        return None
    rows = np.flatnonzero(opaque.any(axis=1))
    cols = np.flatnonzero(opaque.any(axis=0))
    y0, y1 = int(rows[0]), int(rows[-1]) + 1
    x0, x1 = int(cols[0]), int(cols[-1]) + 1
    # np.ascontiguousarray so the cache holds the crop's own bytes rather than
    # a view keeping the whole decoded canvas alive.
    cropped_main = np.ascontiguousarray(main[y0:y1, x0:x1])
    cropped_pc = None if playercolor is None else np.ascontiguousarray(playercolor[y0:y1, x0:x1])
    return cropped_main, cropped_pc, hx - x0, hy - y0


def _tinted(main: np.ndarray, playercolor: np.ndarray | None, team: tuple[int, int, int]):
    """main * team, applied through playercolor's coverage. See the module
    docstring for why this is a multiply and not a palette lookup."""
    if playercolor is None or team == (255, 255, 255):
        return main
    rgb = main[..., :3].astype(np.float32)
    cov = np.where(playercolor[..., 3] > 0, playercolor[..., 0], 0).astype(np.float32) / 255.0
    cov = cov[..., None]
    t = np.array(team, dtype=np.float32) / 255.0
    out = main.copy()
    out[..., :3] = np.clip(rgb * (1 - cov) + rgb * t * cov, 0, 255).astype(np.uint8)
    return out


def _resize_rgba(rgba: np.ndarray, width: int, height: int) -> np.ndarray:
    """Nearest-neighbour box resample. Deliberately not Pillow: this module
    stays Qt-free and image-library-free like the rest of the render path, and
    a sprite shrunk to tile scale is being decimated, not enlarged."""
    src_h, src_w = rgba.shape[:2]
    ys = np.minimum((np.arange(height) * src_h) // height, src_h - 1)
    xs = np.minimum((np.arange(width) * src_w) // width, src_w - 1)
    return rgba[ys[:, None], xs[None, :]]


def sprite_scale(half_w: int) -> float:
    """Native sprite pixels -> canvas pixels, for a projection whose tile
    diamond is 2*half_w wide. One expression, so the mip ladder and any
    tile_px change follow it for free."""
    return 2 * half_w / NATIVE_TILE_W


def _frame_for(unit_const: int, entry: dict, rotation: float) -> int:
    """Which stored frame index `entry`'s graphic resolves to at `rotation`:
    the variant_index/angle_index dispatch, times frame_count.

    **The single frame-dispatch seam every drawing path goes through** --
    _draw_for_entry() for Stepped/Sloped, icon_for() for Flat. Extracted
    (P3-g7) rather than left inline so a future connectivity-derived wall
    frame has exactly one place to change instead of two that can drift.

    `unit_const` is the piece's OWN resolving unit_id, not necessarily the
    unit standing on the map -- see _draw_for_entry()'s own note on that."""
    angle_count = max(1, int(entry["angle_count"]))
    frame_count = max(1, int(entry["frame_count"]))
    if not rotation_is_variant(unit_const):
        return angle_index(rotation, angle_count) * frame_count
    # The file's real frame count, not the .dat's angle_count, bounds a literal
    # stored index -- see variant_index()'s own note on the two cliff families
    # where they disagree. Divided by frame_count to get the real VARIANT slot
    # count rather than the file's total frame count (Tier B plan, 2026-09-06):
    # every wall/cliff const this bound was designed against has frame_count
    # 1, where the two numbers coincide, but Tier B's widening reaches
    # animated variant graphics too (e.g. a decay/death animation, frame_count
    # 30, angle_count 16, 481 real frames -- one shared terminal frame past
    # 16*30) where they do not; passing the raw file total there would let an
    # out-of-angle-range literal (legal under the old angle_index() wrap)
    # resolve past this graphic's real per-variant frame run undetected. None
    # (no install, or the .sld missing here) falls back to angle_count, which
    # is what every caller did before this existed; there is no sprite to draw
    # on that path anyway.
    real_frames = sld_frame_count(str(entry["file_name"]))
    variant_count = None if real_frames is None else max(1, real_frames // frame_count)
    return variant_index(rotation, angle_count, variant_count) * frame_count


def _draw_for_entry(
    unit_const: int, entry: dict, rotation: float, team_index: int, half_w: int
) -> SpriteDraw | None:
    """The tinted, scaled sprite `entry` (one graphic_map() record) resolves
    to, or None on any of the failure paths sprite_for()'s docstring lists.

    `unit_const` is a parameter, not read off `entry`, so a piece can pass its
    OWN resolving unit_id here (see sprite_pieces_for()) while `entry` still
    carries that piece's own file_name/angle_count/frame_count -- a piece's
    frame dispatch is a property of its own graphic, never of whichever unit
    happens to be standing on the map.

    `team_index` is TEAM_COLORS' own index (0 = GAIA, 1..8 = that ColorId's
    tint), not a player_id -- a scenario's stored color override can put any
    player on any tint, so the caller resolves player_id -> team_index
    itself (see scenario_io.LoadedScenario.team_indices) before calling
    here."""
    index = _frame_for(unit_const, entry, rotation)

    scale = sprite_scale(half_w)
    team = TEAM_COLORS[team_index % len(TEAM_COLORS)]
    # Keyed on team_index, not player_id: two scenarios' player 1 can resolve
    # to different stored colors, and this cache is a process-global LRU that
    # would otherwise serve one scenario's tinted sprite to the other's.
    key = (entry["file_name"], index, team_index % len(TEAM_COLORS), half_w)
    hit = _scaled_cache.get_or_none(key)
    if hit is not None:
        return None if hit is _MISS else hit

    native = _native_frame(entry["file_name"], index)
    if native is None:
        _scaled_cache.put(key, _MISS)  # see _MISS -- re-deriving this is expensive
        return None
    main, playercolor, hx, hy = native

    width = max(1, round(main.shape[1] * scale))
    height = max(1, round(main.shape[0] * scale))
    draw = SpriteDraw(
        rgba=_resize_rgba(_tinted(main, playercolor, team), width, height),
        hotspot_x=round(hx * scale),
        hotspot_y=round(hy * scale),
    )
    _scaled_cache.put(key, draw)
    return draw


def sprite_for(
    unit_const: int, rotation: float, team_index: int, half_w: int
) -> SpriteDraw | None:
    """This unit's tinted, scaled sprite, or None to fall back to a mark.

    None is returned, never an exception, for every one of: a unit_const with
    no graphic; no install configured; the .sld missing on this install; the
    file unreadable (bad magic, zero bytes, or a layout variant that is neither
    14 nor 16); a frame index past the file's real end; and a frame whose
    decode raises.

    For a composite building (unit_graphic_map.json's optional "pieces" key),
    this draws only the entry's OWN graphic -- unchanged behavior for every
    existing caller. sprite_pieces_for() is the composite-aware sibling.
    """
    entry = graphic_map().get(unit_const)
    if entry is None:
        return None
    return _draw_for_entry(unit_const, entry, rotation, team_index, half_w)


def sprite_pieces_for(
    unit_const: int, rotation: float, team_index: int, half_w: int
) -> list[SpritePiece]:
    """The full ordered composite for unit_const: ready-to-paste pieces, each
    with its own (dx, dy) screen offset from the unit's own anchor. Empty on
    total failure (no entry, or the parent piece fails to resolve) so the
    caller falls back to today's coloured mark, unchanged. A unit_const with
    no "pieces" key resolves to a single piece at (0, 0) -- callers do not
    need two code paths for a composite vs. a plain unit.

    A non-parent piece that fails to resolve is skipped rather than failing
    the whole composite -- strictly better than today, never worse. Each
    piece resolves through its OWN resolving unit_id (unit_graphic_map.json's
    per-piece "unit_id" -- this const itself for the parent's own piece, an
    annex's unit_id otherwise), never unit_const for every piece: a piece's
    frame dispatch is a property of its own graphic (see _draw_for_entry),
    and pieces can carry a different angle_count/rotation-dispatch than their
    parent even though every currently-composited piece is angle-index-based
    like its parent today.
    """
    entry = graphic_map().get(unit_const)
    if entry is None:
        return []
    pieces_data = entry.get("pieces")
    if not pieces_data:
        draw = _draw_for_entry(unit_const, entry, rotation, team_index, half_w)
        return [] if draw is None else [SpritePiece(draw=draw, dx=0, dy=0)]

    scale = sprite_scale(half_w)
    result: list[SpritePiece] = []
    for piece in pieces_data:
        draw = _draw_for_entry(piece["unit_id"], piece, rotation, team_index, half_w)
        if draw is None:
            # The parent's own piece (unit_id == unit_const) is identified by
            # identity, not list position -- depth order can (and for a town
            # centre's back piece, does) place it anywhere but index 0.
            if piece["unit_id"] == unit_const:
                return []
            continue
        result.append(SpritePiece(
            draw=draw,
            dx=round(piece["dx"] * scale),
            dy=round(piece["dy"] * scale),
        ))
    return result


def _source_over(dst: np.ndarray, base_y: int, base_x: int, src: np.ndarray) -> None:
    """Non-premultiplied source-over of an (h, w, 4) block onto an RGBA canvas,
    in place. No clipping: icon_for()'s canvas is the pieces' own union bbox.

    Deliberately not render._clipped_paint_rgba, which blends into an OPAQUE
    3-channel destination. Over a still-transparent canvas that would blend a
    piece's antialiased edge toward the canvas's zeroed RGB (black) and leave
    a dark halo once the finished icon is finally composited over terrain.
    Here the destination's alpha is part of the result, which is what keeps a
    soft edge soft."""
    h, w = src.shape[:2]
    view = dst[base_y : base_y + h, base_x : base_x + w]
    sa = src[..., 3:4].astype(np.float32) / 255.0
    da = view[..., 3:4].astype(np.float32) / 255.0
    out_a = sa + da * (1.0 - sa)
    rgb = src[..., :3].astype(np.float32) * sa + view[..., :3].astype(np.float32) * da * (1.0 - sa)
    # Guarded divide: a pixel transparent in both operands has out_a == 0 and
    # no colour to recover, so any divisor works -- 1.0 keeps it at zero.
    view[..., :3] = np.clip(rgb / np.where(out_a > 0, out_a, 1.0), 0, 255).astype(np.uint8)
    view[..., 3:4] = np.clip(out_a * 255.0, 0, 255).astype(np.uint8)


def _native_piece(unit_const: int, entry: dict, rotation: float, team) -> SpriteDraw | None:
    """One piece resolved and tinted at NATIVE scale -- _draw_for_entry()'s
    body with the scaling and the _scaled_cache put both left out."""
    native = _native_frame(entry["file_name"], _frame_for(unit_const, entry, rotation))
    if native is None:
        return None
    main, playercolor, hx, hy = native
    return SpriteDraw(rgba=_tinted(main, playercolor, team), hotspot_x=hx, hotspot_y=hy)


def _native_pieces_for(unit_const: int, entry: dict, rotation: float, team) -> list[SpritePiece]:
    """sprite_pieces_for()'s walk at native scale: same parent-by-identity
    rule, same skip-a-failed-non-parent rule, dx/dy unscaled.

    **Why not sprite_pieces_for(..., half_w=NATIVE_TILE_W // 2)**, which is
    sprite_scale() == 1.0 exactly and would be less code: _draw_for_entry()
    unconditionally puts its result into _scaled_cache, so every icon build
    would deposit a tinted NATIVE-size frame (a Wonder is ~500x400) into an
    LRU whose capacity P3-g4 sized for decimated tile-scale sprites --
    evicting Stepped's and Sloped's live entries to hold intermediates thrown
    away one line later. That is exactly the regression P3-g4's "sprites were
    cached uncropped" finding fixed (7.27x -> 1.14x composite, ~8x memory)."""
    pieces_data = entry.get("pieces")
    if not pieces_data:
        draw = _native_piece(unit_const, entry, rotation, team)
        return [] if draw is None else [SpritePiece(draw=draw, dx=0, dy=0)]

    result: list[SpritePiece] = []
    for piece in pieces_data:
        draw = _native_piece(piece["unit_id"], piece, rotation, team)
        if draw is None:
            # Parent identified by identity, not list position -- see
            # sprite_pieces_for()'s own note on why.
            if piece["unit_id"] == unit_const:
                return []
            continue
        result.append(SpritePiece(draw=draw, dx=int(piece["dx"]), dy=int(piece["dy"])))
    return result


def _assembled_native(pieces: list[SpritePiece]) -> np.ndarray | None:
    """The pieces flattened into one RGBA array at their native offsets, in
    list order (which sprite_pieces_for() already establishes as depth order).

    A single piece IS the assembly -- returned as-is rather than copied
    through a composite, which is the overwhelmingly common case (every
    non-composite unit_const) and the one worth not paying for."""
    if not pieces:
        return None
    if len(pieces) == 1:
        return pieces[0].draw.rgba

    rects = []
    for piece in pieces:
        h, w = piece.draw.rgba.shape[:2]
        x0 = piece.dx - piece.draw.hotspot_x
        y0 = piece.dy - piece.draw.hotspot_y
        rects.append((x0, y0, x0 + w, y0 + h))
    ox = min(r[0] for r in rects)
    oy = min(r[1] for r in rects)
    out = np.zeros((max(r[3] for r in rects) - oy, max(r[2] for r in rects) - ox, 4), dtype=np.uint8)
    for piece, (x0, y0, _x1, _y1) in zip(pieces, rects):
        _source_over(out, y0 - oy, x0 - ox, piece.draw.rgba)
    return out


def _frame_key(unit_const: int, entry: dict, rotation: float) -> tuple[int, ...]:
    """icon_for()'s cache key's frame component: every piece's own _frame_for()
    result, length 1 for a non-composite const.

    Keying on the raw `rotation` instead would blow the LRU on arbitrary float
    rotations (measured: 34 distinct values across the corpus, plus off-grid
    outliers). Keying on the PARENT's frame alone would collide whenever a
    piece carries a different angle_count from its parent, which
    sprite_pieces_for()'s own docstring explicitly allows."""
    pieces_data = entry.get("pieces")
    if not pieces_data:
        return (_frame_for(unit_const, entry, rotation),)
    return tuple(_frame_for(piece["unit_id"], piece, rotation) for piece in pieces_data)


def icon_for(
    unit_const: int, rotation: float, team_index: int, footprint_w: int, footprint_h: int
) -> SpriteDraw | None:
    """This unit's sprite fitted into a footprint_w x footprint_h pixel rect --
    Flat mode's counterpart to sprite_for() (P3-g7). None to fall back to the
    coloured rect, on every failure sprite_for()'s docstring lists.

    **Aspect-preserving contain-fit, and the "never leaves the footprint"
    property is load-bearing, not cosmetic.** Flat is a top-down square grid,
    not an isometric one, so a 2:1 iso sprite has no natural placement there;
    an icon that fits inside its own footprint rect is what lets Flat's
    existing per-tile edit rects and exact canvas sizing stay sufficient, with
    none of the dirty-bbox widening, canvas headroom or MAX_SPRITE_REACH_*
    machinery Stepped and Sloped need. Stretch-to-fill was the alternative and
    was rejected: a villager's native ink is 15x39, so filling a 64x64 cell is
    a 4.3x horizontal distortion that reads as a blob.

    hotspot_x/y are 0: an icon is placed by its own rect, not by a hotspot,
    and carrying a stale iso hotspot on it is how it would silently get
    blitted off its footprint.

    footprint_w/h come from the CLAMPED unit_tile_bounds() rect, so a building
    hanging off a map edge fits the rect actually painted."""
    if footprint_w <= 0 or footprint_h <= 0:
        return None
    entry = graphic_map().get(unit_const)
    if entry is None:
        return None

    team_slot = team_index % len(TEAM_COLORS)
    key = (unit_const, _frame_key(unit_const, entry, rotation), team_slot, footprint_w, footprint_h)
    hit = _icon_cache.get_or_none(key)
    if hit is not None:
        return None if hit is _MISS else hit

    draw = _build_icon(unit_const, entry, rotation, TEAM_COLORS[team_slot], footprint_w, footprint_h)
    _icon_cache.put(key, _MISS if draw is None else draw)  # see _MISS
    return draw


def _build_icon(
    unit_const: int, entry: dict, rotation: float, team, fw: int, fh: int
) -> SpriteDraw | None:
    """icon_for()'s uncached body."""
    assembly = _assembled_native(_native_pieces_for(unit_const, entry, rotation, team))
    if assembly is None:
        return None
    cropped = _cropped_to_ink(assembly, None, 0, 0)
    if cropped is None:
        return None
    ink = cropped[0]
    ink_h, ink_w = ink.shape[:2]
    scale = min(fw / ink_w, fh / ink_h)
    # The min(fw/fh, ...) clamp is a guard, not a live correction, and that was
    # MEASURED rather than assumed: with the scale above, ink_w * scale <= fw
    # holds and float error is nowhere near the 0.5 a round() would need to
    # cross the boundary, so dropping the clamp leaves the whole suite green.
    # It is kept because it is what still holds when the SCALE regresses --
    # tests/test_flat_sprites.py's mutation arm drops the vertical constraint
    # (scale = fw / ink_w) and this clamp is the only thing then keeping the
    # icon inside its footprint at all.
    iw = min(fw, max(1, round(ink_w * scale)))
    ih = min(fh, max(1, round(ink_h * scale)))
    return SpriteDraw(rgba=_resize_rgba(ink, iw, ih), hotspot_x=0, hotspot_y=0)


def anchor_tile_coords(
    tile_x0: int, tile_y0: int, span_x: int, span_y: int
) -> tuple[float, float]:
    """The continuous tile coordinate a sprite's hotspot sits on: the
    FOOTPRINT'S CENTRE, not the anchor tile's diamond centre (those differ by
    half a tile on an even span) and not the sprite's top-left corner, which is
    what a naive blit does and what offsets every sprite from its tile.

    Verified against the game's own art: a 3x3 Barracks' stone base lands on
    exactly its own footprint diamond under this rule, with only the palisade
    overhanging -- which is what it does in game."""
    return tile_x0 + span_x / 2, tile_y0 + span_y / 2


def sprite_anchor_tile(tiles: list[tuple[int, int]]) -> tuple[int, int]:
    """Which footprint tile's moment in the depth walk paints the sprite, out
    of `tiles` -- the unit's real occupied set (render.unit_occupied_tiles()):
    its whole bbox for an ordinary building, the sparse 6-tile set for a
    diagonal gate. Taking the occupied set rather than a rect here is what
    fixes a diagonal gate's sprite anchoring on a tile its footprint doesn't
    actually cover (Part 2's reported wrong-depth-position defect).

    A sprite is ONE image over the whole footprint, so it must paint once --
    unlike the diamond path, where _units_by_tile buckets a building into every
    footprint tile and each diamond lands at its own tile's depth position.

    The tile chosen is the one that comes LAST in depth_order: maximal
    d = y - x, tie-broken on ascending x, the same key composite_rect_iso's own
    np.lexsort((xs, ys - xs)) uses. Reusing that key rather than an ad-hoc
    max(x + y) matters because a divergence here is a paint-order mismatch that
    tests/test_unit_pick.py's ID-plane oracle cannot catch -- picking still goes
    through the diamond path and is unaffected by sprites.

    Painting last within the footprint means every footprint tile's terrain is
    already down, while terrain nearer than the building still paints over the
    sprite, exactly as it does for diamonds today.
    """
    best = None
    for tx, ty in tiles:
        key = (ty - tx, tx)
        if best is None or key > best[0]:
            best = (key, (tx, ty))
    return best[1]
